package com.citacloud.springboot.contacloud.app.repositories;
import com.citacloud.springboot.contacloud.app.models.*;import jakarta.persistence.LockModeType;import org.springframework.data.domain.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;import java.time.LocalDate;import java.util.*;
public interface SupplierCreditNoteRepository extends JpaRepository<NotaCreditoProveedor,UUID>{
 @EntityGraph(attributePaths={"proveedor","moneda","facturaRelacionada"}) @Query("select n from NotaCreditoProveedor n left join n.facturaRelacionada f where n.tenantId=:tenant and n.empresaId=:empresa and (:proveedor is null or n.proveedorId=:proveedor) and (:estado is null or n.status=:estado) and (:desde is null or n.fecha>=:desde) and (:hasta is null or n.fecha<=:hasta) and (:buscar='' or lower(n.numero) like lower(concat('%',:buscar,'%')) or lower(n.numeroProveedor) like lower(concat('%',:buscar,'%')) or lower(coalesce(n.numeroFiscal,'')) like lower(concat('%',:buscar,'%')) or lower(n.proveedor.nombreComercial) like lower(concat('%',:buscar,'%')) or lower(coalesce(f.numeroProveedor,'')) like lower(concat('%',:buscar,'%')))")
 Page<NotaCreditoProveedor> buscar(@Param("tenant")UUID tenant,@Param("empresa")UUID empresa,@Param("buscar")String buscar,@Param("proveedor")UUID proveedor,@Param("estado")EstadoNotaCreditoProveedor estado,@Param("desde")LocalDate desde,@Param("hasta")LocalDate hasta,Pageable pageable);
 @EntityGraph(attributePaths={"lineas","proveedor","moneda","facturaRelacionada"}) Optional<NotaCreditoProveedor> findByIdAndTenantIdAndEmpresaId(UUID id,UUID tenant,UUID empresa);
 @Lock(LockModeType.PESSIMISTIC_WRITE) @EntityGraph(attributePaths={"lineas","proveedor","moneda","facturaRelacionada"}) @Query("select n from NotaCreditoProveedor n where n.id=:id and n.tenantId=:tenant and n.empresaId=:empresa") Optional<NotaCreditoProveedor> bloquear(@Param("id")UUID id,@Param("tenant")UUID tenant,@Param("empresa")UUID empresa);
 boolean existsByTenantIdAndEmpresaIdAndProveedorIdAndNumeroProveedorNormalizado(UUID tenant,UUID empresa,UUID proveedor,String numero);
 boolean existsByTenantIdAndEmpresaIdAndProveedorIdAndNumeroProveedorNormalizadoAndIdNot(UUID tenant,UUID empresa,UUID proveedor,String numero,UUID id);
 @Query("select coalesce(sum(n.total-n.aplicado),0) from NotaCreditoProveedor n where n.tenantId=:tenant and n.empresaId=:empresa and n.proveedorId=:proveedor and n.monedaId=:moneda and n.status in (com.citacloud.springboot.contacloud.app.models.EstadoNotaCreditoProveedor.AVAILABLE,com.citacloud.springboot.contacloud.app.models.EstadoNotaCreditoProveedor.PARTIALLY_APPLIED)") java.math.BigDecimal disponibleProveedor(@Param("tenant")UUID tenant,@Param("empresa")UUID empresa,@Param("proveedor")UUID proveedor,@Param("moneda")UUID moneda);
}
