package com.citacloud.springboot.contacloud.app.services;
import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.models.*;import com.citacloud.springboot.contacloud.app.multitenancy.DirectoryGateway;
import com.citacloud.springboot.contacloud.app.repositories.*;import com.citacloud.springboot.contacloud.app.security.TenantContext;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.data.domain.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.util.*;import java.util.stream.Collectors;
@Service
public class EmpresaAdministracionService {
    private final EmpresaRepository empresas;private final DatosEmpresaRepository datos;private final SucursalRepository sucursales;private final MonedaRepository monedas;private final RolRepository roles;private final UsuarioRepository usuarios;private final UsuarioEmpresaRepository accesos;private final EmpresaModuloRepository empresaModulos;private final EmpresaModuloService moduloService;private final JdbcTemplate jdbc;private final AuditoriaService auditoria;
    @Autowired(required=false) private DirectoryGateway directory;
    public EmpresaAdministracionService(EmpresaRepository empresas,DatosEmpresaRepository datos,SucursalRepository sucursales,MonedaRepository monedas,RolRepository roles,UsuarioRepository usuarios,UsuarioEmpresaRepository accesos,EmpresaModuloRepository empresaModulos,EmpresaModuloService moduloService,JdbcTemplate jdbc,AuditoriaService auditoria){this.empresas=empresas;this.datos=datos;this.sucursales=sucursales;this.monedas=monedas;this.roles=roles;this.usuarios=usuarios;this.accesos=accesos;this.empresaModulos=empresaModulos;this.moduloService=moduloService;this.jdbc=jdbc;this.auditoria=auditoria;}
    @Transactional(readOnly=true) @PreAuthorize("hasAuthority('empresas.ver')")
    public Page<EmpresaResumenDto> buscar(String texto,Boolean activo,int pagina,int tamano){if(pagina<0||!Set.of(10,25,50,100).contains(tamano))throw new IllegalArgumentException("Paginación inválida.");var p=TenantContext.principalActual();Pageable pageable=PageRequest.of(pagina,tamano,Sort.by("nombre").ascending());Page<Empresa> page=activo==null?empresas.buscarAutorizadas(p.tenantId(),p.usuarioId(),limpiar(texto),pageable):empresas.buscarAutorizadasPorEstado(p.tenantId(),p.usuarioId(),limpiar(texto),activo,pageable);List<UUID> ids=page.getContent().stream().map(Empresa::getId).toList();Map<UUID,Long> counts=ids.isEmpty()?Map.of():empresaModulos.findAllByTenantIdAndEmpresaIdInAndEnabledTrue(p.tenantId(),ids).stream().collect(Collectors.groupingBy(EmpresaModulo::getEmpresaId,Collectors.counting()));return page.map(e->new EmpresaResumenDto(e.getId(),e.getNombre(),e.getIdentificacionFiscal(),counts.getOrDefault(e.getId(),0L),"Base asignada al tenant",e.isActivo()));}
    @Transactional @PreAuthorize("hasAuthority('empresas.crear')")
    public EmpresaResumenDto crearEnTenantActual(NuevaEmpresaDto input){validar(input);var principal=TenantContext.principalActual();String codigo=generarCodigo(input.nombreComercial());Empresa empresa=new Empresa(principal.tenantId(),codigo,input.nombreComercial().trim());empresa.setIdentificacionFiscal(limpiarNulo(input.identificacionFiscal()));empresas.saveAndFlush(empresa);DatosEmpresa de=new DatosEmpresa(empresa.getId(),input.nombreComercial().trim());de.setRazonSocial(limpiarNulo(input.razonSocial()));de.setTelefono(CompanyConfigurationService.normalizePhone(input.telefono()));de.setCorreo(CompanyConfigurationService.normalizeEmail(input.correo()));de.setDireccion(limpiarNulo(input.direccion()));datos.save(de);Sucursal principalSucursal=new Sucursal(empresa.getId(),"PRINCIPAL","Sucursal Principal");principalSucursal.setPrincipal(true);sucursales.save(principalSucursal);Moneda dop=new Moneda(empresa.getId(),"DOP","Peso dominicano","RD$",(short)2);dop.setMonedaBase(true);monedas.save(dop);
        Rol admin=new Rol(empresa.getId(),"ADMINISTRADOR","Administrador");admin.setProtegido(true);roles.saveAndFlush(admin);jdbc.update("insert into rol_permisos(empresa_id,rol_id,permiso_id) select ?,?,id from permisos",empresa.getId(),admin.getId());Usuario creador=usuarios.findByIdAndTenantId(principal.usuarioId(),principal.tenantId()).orElseThrow(()->new ReglaNegocioException("No se encontró la identidad del usuario creador."));UsuarioEmpresa acceso=new UsuarioEmpresa(creador,empresa.getId(),admin);acceso.setAccesoTodasSucursales(true);accesos.save(acceso);boolean puedeElegir=principal.permisos().contains("empresas.configurar_modulos");moduloService.configurarInicial(principal.tenantId(),empresa.getId(),input.moduleKeys(),puedeElegir);if(directory!=null)directory.registerCompany(empresa.getId(),principal.tenantId(),codigo,empresa.getNombre());auditoria.registrar("COMPANY_CREATED","Empresa",empresa.getId(),"{}");return new EmpresaResumenDto(empresa.getId(),empresa.getNombre(),empresa.getIdentificacionFiscal(),empresaModulos.findEnabledKeys(principal.tenantId(),empresa.getId()).size(),"Base asignada al tenant",true);}
    @Transactional @PreAuthorize("hasAuthority('empresas.desactivar')") public void desactivar(UUID empresaId){validarAcceso(empresaId);var p=TenantContext.principalActual();Empresa e=empresas.findByIdAndTenantId(empresaId,p.tenantId()).orElseThrow(()->new RecursoNoEncontradoException("Empresa no encontrada."));if(e.getId().equals(p.empresaId()))throw new ReglaNegocioException("No puede desactivar la empresa de la sesión actual.");e.setActivo(false);empresas.save(e);auditoria.registrar("COMPANY_DISABLED","Empresa",e.getId(),"{}");}
    @Transactional(readOnly=true) @PreAuthorize("hasAuthority('empresas.ver')") public List<ModuloEmpresaDto> modulos(UUID empresaId){validarAcceso(empresaId);var p=TenantContext.principalActual();return moduloService.listar(p.tenantId(),empresaId);}
    @Transactional @PreAuthorize("hasAuthority('empresas.configurar_modulos')") public void configurarModulos(UUID empresaId,Set<String> keys){validarAcceso(empresaId);var p=TenantContext.principalActual();moduloService.configurar(p.tenantId(),empresaId,keys);}
    private void validarAcceso(UUID empresaId){var p=TenantContext.principalActual();empresas.findByIdAndTenantId(empresaId,p.tenantId()).orElseThrow(()->new RecursoNoEncontradoException("Empresa no encontrada."));accesos.findByUsuarioIdAndEmpresaId(p.usuarioId(),empresaId).filter(UsuarioEmpresa::isActivo).orElseThrow(()->new ReglaNegocioException("No tiene acceso a la empresa solicitada."));}
    private String generarCodigo(String nombre){String base=nombre.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]","");if(base.isBlank())base="EMPRESA";base=base.substring(0,Math.min(12,base.length()));String code;do{code=base+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase(Locale.ROOT);}while(empresas.existsByCodigoIgnoreCase(code));return code;}
    private static void validar(NuevaEmpresaDto i){if(i==null||limpiar(i.nombreComercial()).isEmpty())throw new ReglaNegocioException("El nombre comercial es obligatorio.");if(limpiar(i.nombreComercial()).length()>150)throw new ReglaNegocioException("El nombre comercial excede 150 caracteres.");}
    private static String limpiar(String v){return v==null?"":v.trim();}private static String limpiarNulo(String v){String x=limpiar(v);return x.isEmpty()?null:x;}
}
