package com.citacloud.springboot.contacloud.app.services;
import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.models.*;import com.citacloud.springboot.contacloud.app.multitenancy.DirectoryGateway;
import com.citacloud.springboot.contacloud.app.repositories.*;import com.citacloud.springboot.contacloud.app.security.TenantContext;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.data.domain.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.util.*;import java.util.stream.Collectors;
@Service
public class EmpresaAdministracionService {
    private final EmpresaRepository empresas;private final DatosEmpresaRepository datos;private final UsuarioEmpresaRepository accesos;private final EmpresaModuloRepository empresaModulos;private final EmpresaModuloService moduloService;private final AuditoriaService auditoria;
    private final SucursalRepository sucursales;private final MonedaRepository monedas;private final RolRepository roles;private final PermisoRepository permisos;private final RolPermisoRepository rolPermisos;private final UsuarioRepository usuarios;private final PasswordEncoder passwordEncoder;
    @Autowired(required=false) private DirectoryGateway directory;
    public EmpresaAdministracionService(EmpresaRepository empresas,DatosEmpresaRepository datos,UsuarioEmpresaRepository accesos,EmpresaModuloRepository empresaModulos,EmpresaModuloService moduloService,AuditoriaService auditoria,SucursalRepository sucursales,MonedaRepository monedas,RolRepository roles,PermisoRepository permisos,RolPermisoRepository rolPermisos,UsuarioRepository usuarios,PasswordEncoder passwordEncoder){this.empresas=empresas;this.datos=datos;this.accesos=accesos;this.empresaModulos=empresaModulos;this.moduloService=moduloService;this.auditoria=auditoria;this.sucursales=sucursales;this.monedas=monedas;this.roles=roles;this.permisos=permisos;this.rolPermisos=rolPermisos;this.usuarios=usuarios;this.passwordEncoder=passwordEncoder;}
    @Transactional @PreAuthorize("hasAuthority('empresas.crear')")
    public ProvisioningResult crearTenantLocal(NuevaEmpresaDto input,UsuarioInicialDto usuarioInicial,String clave,String confirmarClave){
        validarCreacion(input);String codigo=CodigoEmpresaValidator.validarYNormalizar(input.codigo());UsuarioInicialDto usuarioValidado=UsuarioInicialValidator.validar(usuarioInicial,clave,confirmarClave);var actor=TenantContext.principalActual();
        if(empresas.existsByCodigoIgnoreCase(codigo))throw new ReglaNegocioException("El código de acceso ya está siendo utilizado por otra empresa.");
        Set<String> moduleKeys=input.moduleKeys()==null?Set.of():input.moduleKeys();
        if(!moduleKeys.isEmpty()&&!actor.permisos().contains("empresas.configurar_modulos"))throw new ReglaNegocioException("No tiene permiso para configurar módulos.");
        UUID tenantId=UUID.randomUUID();Empresa empresa=new Empresa(tenantId,codigo,input.nombreComercial().trim());empresa.setIdentificacionFiscal(CompanyConfigurationService.normalizeRnc(input.identificacionFiscal()));empresa=empresas.saveAndFlush(empresa);
        DatosEmpresa dato=new DatosEmpresa(empresa.getId(),empresa.getNombre());dato.setRazonSocial(limpiarNulo(input.razonSocial()));dato.setTelefono(CompanyConfigurationService.normalizePhone(input.telefono()));dato.setCorreo(CompanyConfigurationService.normalizeEmail(input.correo()));dato.setDireccion(limpiarNulo(input.direccion()));datos.save(dato);
        Sucursal sucursal=new Sucursal(empresa.getId(),"PRINCIPAL","Sucursal Principal");sucursal.setPrincipal(true);sucursales.save(sucursal);
        Moneda moneda=new Moneda(empresa.getId(),"DOP","Peso dominicano","RD$",(short)2);moneda.setMonedaBase(true);monedas.save(moneda);
        Rol rol=new Rol(empresa.getId(),"ADMINISTRADOR","Administrador");rol.setProtegido(true);rol=roles.saveAndFlush(rol);
        UUID empresaId=empresa.getId(),rolId=rol.getId();List<RolPermiso> asignaciones=permisos.findAllByOrderByModuloAscRecursoAscCodigoAsc().stream().filter(p->PermisoTenantPolicy.disponibleParaAdministradorInicial(p.getModulo(),p.getRecurso())).map(p->new RolPermiso(tenantId,empresaId,rolId,p.getId())).toList();rolPermisos.saveAll(asignaciones);
        Usuario usuario=new Usuario(tenantId,empresa.getId(),usuarioValidado.usuario(),usuarioValidado.nombre(),usuarioValidado.apellido(),passwordEncoder.encode(clave));usuario.setCorreo(usuarioValidado.correo());usuario.setTelefono(usuarioValidado.telefono());usuario=usuarios.saveAndFlush(usuario);
        accesos.save(new UsuarioEmpresa(usuario,empresa.getId(),rol));
        moduloService.configurarInicial(tenantId,empresa.getId(),moduleKeys,actor.permisos().contains("empresas.configurar_modulos"));
        auditoria.registrarPara(empresa.getId(),usuario.getId(),"TENANT_CREATED","Tenant",tenantId,"{}");
        return new ProvisioningResult(tenantId,empresa.getId(),codigo,"conta_cloud","ACTIVE");
    }
    @Transactional(readOnly=true) @PreAuthorize("hasAuthority('empresas.ver')")
    public Page<EmpresaResumenDto> buscar(String texto,Boolean activo,int pagina,int tamano){if(pagina<0||!Set.of(10,25,50,100).contains(tamano))throw new IllegalArgumentException("Paginación inválida.");Pageable pageable=PageRequest.of(pagina,tamano,Sort.by("nombre").ascending());Page<Empresa> page=activo==null?empresas.buscarTodas(limpiar(texto),pageable):empresas.buscarTodasPorEstado(limpiar(texto),activo,pageable);List<UUID> ids=page.getContent().stream().map(Empresa::getId).toList();Map<UUID,Long> counts=ids.isEmpty()?Map.of():empresaModulos.findAllByEmpresaIdInAndEnabledTrue(ids).stream().collect(Collectors.groupingBy(EmpresaModulo::getEmpresaId,Collectors.counting()));return page.map(e->new EmpresaResumenDto(e.getId(),e.getCodigo(),e.getNombre(),e.getIdentificacionFiscal(),counts.getOrDefault(e.getId(),0L),"Base asignada al tenant",e.isActivo()));}
    @Transactional(readOnly=true) @PreAuthorize("hasAnyAuthority('empresas.ver','empresas.editar','empresas.configurar_modulos','empresas.resetear_contrasena')") public EmpresaDetalleDto obtener(UUID empresaId){Empresa e=empresaGlobal(empresaId);DatosEmpresa d=datos.findByEmpresaId(empresaId).orElseGet(()->new DatosEmpresa(empresaId,e.getNombre()));return new EmpresaDetalleDto(e.getId(),e.getCodigo(),valor(d.getNombreComercial(),e.getNombre()),d.getRazonSocial(),e.getIdentificacionFiscal(),d.getTelefono(),d.getCorreo(),d.getDireccion(),e.isActivo());}
    @Transactional @PreAuthorize("hasAuthority('empresas.editar')") public void actualizar(UUID empresaId,ActualizarEmpresaDto input){validarEdicion(input);Empresa e=empresaGlobal(empresaId);e.setNombre(input.nombreComercial().trim());e.setIdentificacionFiscal(CompanyConfigurationService.normalizeRnc(input.identificacionFiscal()));empresas.save(e);DatosEmpresa d=datos.findByEmpresaId(empresaId).orElseGet(()->new DatosEmpresa(empresaId,e.getNombre()));aplicarDatos(d,input);datos.save(d);if(directory!=null){directory.registerCompany(e.getId(),e.getTenantId(),e.getCodigo(),e.getNombre());directory.setCompanyActive(e.getId(),e.isActivo());}auditoria.registrar("COMPANY_UPDATED","Empresa",e.getId(),"{}");}
    @Transactional @PreAuthorize("hasAuthority('empresas.desactivar')") public void desactivar(UUID empresaId){var p=TenantContext.principalActual();Empresa e=empresaGlobal(empresaId);if(e.getId().equals(p.empresaId()))throw new ReglaNegocioException("No puede desactivar la empresa de la sesión actual.");e.setActivo(false);empresas.save(e);if(directory!=null)directory.setCompanyActive(e.getId(),false);auditoria.registrar("COMPANY_DISABLED","Empresa",e.getId(),"{}");}
    @Transactional @PreAuthorize("hasAuthority('empresas.activar')") public void activar(UUID empresaId){Empresa e=empresaGlobal(empresaId);if(e.isActivo())return;e.setActivo(true);empresas.save(e);if(directory!=null)directory.setCompanyActive(e.getId(),true);auditoria.registrar("COMPANY_ENABLED","Empresa",e.getId(),"{}");}
    @Transactional(readOnly=true) @PreAuthorize("hasAuthority('empresas.resetear_contrasena')") public List<UsuarioEmpresaClaveDto> usuariosParaReset(UUID empresaId){Empresa empresa=empresaGlobal(empresaId);return accesos.findAllForPasswordReset(empresaId).stream().filter(a->empresa.getTenantId().equals(a.getUsuario().getTenantId())).map(a->{Usuario u=a.getUsuario();String nombre=(limpiar(u.getNombre())+" "+limpiar(u.getApellido())).trim();return new UsuarioEmpresaClaveDto(u.getId(),u.getUsuario(),nombre,a.isActivo()&&u.isActivo());}).toList();}
    @Transactional @PreAuthorize("hasAuthority('empresas.resetear_contrasena')") public void resetearContrasena(UUID empresaId,UUID usuarioId,String clave,String confirmarClave){Empresa empresa=empresaGlobal(empresaId);if(usuarioId==null)throw new ReglaNegocioException("Seleccione un usuario.");UsuarioEmpresa acceso=accesos.findByUsuarioIdAndEmpresaId(usuarioId,empresaId).orElseThrow(()->new RecursoNoEncontradoException("El usuario no pertenece a la empresa seleccionada."));Usuario usuario=acceso.getUsuario();if(!empresa.getTenantId().equals(usuario.getTenantId()))throw new ReglaNegocioException("El usuario no corresponde al tenant de la empresa.");validarNuevaContrasena(clave,confirmarClave);int actualizados=usuarios.actualizarPasswordHash(usuarioId,empresa.getTenantId(),passwordEncoder.encode(clave));if(actualizados!=1)throw new RecursoNoEncontradoException("No fue posible localizar el usuario dentro del tenant.");auditoria.registrar("CONTRASENA_USUARIO_RESETEADA","Usuario",usuarioId,"{}");}
    @Transactional(readOnly=true) @PreAuthorize("hasAuthority('empresas.ver')") public List<ModuloEmpresaDto> modulos(UUID empresaId){Empresa e=empresaGlobal(empresaId);return moduloService.listarAdministracion(e.getTenantId(),empresaId);}
    @Transactional @PreAuthorize("hasAuthority('empresas.configurar_modulos')") public void configurarModulos(UUID empresaId,Set<String> keys){Empresa e=empresaGlobal(empresaId);moduloService.configurarAdministracion(e.getTenantId(),empresaId,keys);}
    private static void aplicarDatos(DatosEmpresa datos,ActualizarEmpresaDto input){datos.setNombreComercial(input.nombreComercial().trim());datos.setRazonSocial(limpiarNulo(input.razonSocial()));datos.setTelefono(CompanyConfigurationService.normalizePhone(input.telefono()));datos.setCorreo(CompanyConfigurationService.normalizeEmail(input.correo()));datos.setDireccion(limpiarNulo(input.direccion()));}
    private Empresa empresaGlobal(UUID empresaId){return empresas.findById(empresaId).orElseThrow(()->new RecursoNoEncontradoException("Empresa no encontrada."));}
    private static void validarEdicion(ActualizarEmpresaDto i){if(i==null||limpiar(i.nombreComercial()).isEmpty())throw new ReglaNegocioException("El nombre comercial es obligatorio.");if(limpiar(i.nombreComercial()).length()>150)throw new ReglaNegocioException("El nombre comercial excede 150 caracteres.");if(limpiar(i.razonSocial()).length()>150)throw new ReglaNegocioException("La razón social excede 150 caracteres.");if(limpiar(i.direccion()).length()>255)throw new ReglaNegocioException("La dirección excede 255 caracteres.");}
    private static void validarCreacion(NuevaEmpresaDto i){if(i==null)throw new ReglaNegocioException("Los datos de la empresa son obligatorios.");validarEdicion(new ActualizarEmpresaDto(i.nombreComercial(),i.razonSocial(),i.identificacionFiscal(),i.telefono(),i.correo(),i.direccion()));}
    private static void validarNuevaContrasena(String clave,String confirmar){String a=clave==null?"":clave;String b=confirmar==null?"":confirmar;if(a.length()<8||a.length()>72)throw new ReglaNegocioException("La contraseña debe tener entre 8 y 72 caracteres.");if(!a.equals(b))throw new ReglaNegocioException("Las contraseñas no coinciden.");}
    private static String valor(String preferido,String alterno){return limpiar(preferido).isEmpty()?alterno:preferido;}
    private static String limpiar(String v){return v==null?"":v.trim();}private static String limpiarNulo(String v){String x=limpiar(v);return x.isEmpty()?null:x;}
}
