package com.citacloud.springboot.contacloud.app.services;
import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.models.Impuesto;import com.citacloud.springboot.contacloud.app.repositories.ImpuestoRepository;import com.citacloud.springboot.contacloud.app.security.*;import org.springframework.data.domain.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;
@Service public class ImpuestoFiscalService{
 private final ImpuestoRepository repo;private final AuditoriaService auditoria;public ImpuestoFiscalService(ImpuestoRepository r,AuditoriaService a){repo=r;auditoria=a;}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('IMPUESTOS') and hasAuthority('impuestos.ver')") public Page<ImpuestoFiscalDto> buscar(String q,Boolean activo,int page,int size){return repo.buscar(TenantContext.requerirTenantId(),EmpresaContext.requerirEmpresaId(),texto(q),activo,PageRequest.of(page,size)).map(ImpuestoFiscalService::dto);}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('IMPUESTOS') and hasAuthority('impuestos.ver')") public ImpuestoFiscalDto obtener(UUID id){return dto(seguro(id));}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('IMPUESTOS') and hasAuthority('impuestos.crear')") public ImpuestoFiscalDto crear(ImpuestoFiscalInput in){validar(in);UUID id=UUID.randomUUID();var x=new Impuesto(TenantContext.requerirTenantId(),EmpresaContext.requerirEmpresaId(),"IMP-"+id.toString().substring(0,8).toUpperCase(Locale.ROOT),in.nombre().trim(),in.tasa(),textoNulo(in.descripcion()));x=repo.save(x);auditoria.registrar("CREAR","Impuesto",x.getId(),"{}");return dto(x);}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('IMPUESTOS') and hasAuthority('impuestos.editar')") public ImpuestoFiscalDto actualizar(UUID id,ImpuestoFiscalInput in){validar(in);var x=seguro(id);x.setNombre(in.nombre().trim());x.setPorcentaje(in.tasa());x.setDescripcion(textoNulo(in.descripcion()));auditoria.registrar("EDITAR","Impuesto",id,"{}");return dto(x);}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('IMPUESTOS') and hasAuthority('impuestos.desactivar')") public void cambiarEstado(UUID id,boolean activo){var x=seguro(id);x.setActivo(activo);auditoria.registrar(activo?"ACTIVAR":"DESACTIVAR","Impuesto",id,"{}");}
 private Impuesto seguro(UUID id){return repo.findByIdAndTenantIdAndEmpresaId(id,TenantContext.requerirTenantId(),EmpresaContext.requerirEmpresaId()).orElseThrow(()->new RecursoNoEncontradoException("Impuesto no encontrado."));}
 static void validar(ImpuestoFiscalInput in){if(in==null||in.nombre()==null||in.nombre().isBlank())throw new ReglaNegocioException("El nombre es obligatorio.");if(in.tasa()==null)throw new ReglaNegocioException("La tasa es obligatoria.");if(in.tasa().compareTo(BigDecimal.ZERO)<0||in.tasa().compareTo(new BigDecimal("100"))>0)throw new ReglaNegocioException("La tasa debe estar entre 0 y 100.");}
 private static ImpuestoFiscalDto dto(Impuesto x){return new ImpuestoFiscalDto(x.getId(),x.getNombre(),x.getPorcentaje(),"PORCENTAJE",x.getDescripcion(),x.isActivo());}private static String texto(String x){return x==null?"":x.trim();}private static String textoNulo(String x){String v=texto(x);return v.isEmpty()?null:v;}
}
