package com.citacloud.springboot.contacloud.app.services;

import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.mappers.SupplierCreditNoteMapper;
import com.citacloud.springboot.contacloud.app.models.*;import com.citacloud.springboot.contacloud.app.repositories.*;
import com.citacloud.springboot.contacloud.app.security.*;import org.springframework.data.domain.*;import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.math.*;import java.text.Normalizer;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

@Service public class SupplierCreditNoteService{
 private static final Set<Integer> SIZES=Set.of(10,25,50,100);
 private final SupplierCreditNoteRepository notes;private final SupplierCreditNoteLineRepository noteLines;private final SupplierCreditApplicationRepository applications;
 private final SupplierRepository suppliers;private final PurchaseInvoiceRepository invoices;private final AccountsPayableRepository payables;
 private final MonedaRepository currencies;private final TasaCambioRepository exchangeRates;private final ImpuestoRepository taxes;private final ProductRepository products;
 private final PurchaseOrderCalculationService calculations;private final SupplierCreditNoteNumberService numbers;private final SupplierCreditNoteMapper mapper;private final AuditoriaService audit;
 private final EmpresaRepository companies;private final DatosEmpresaRepository companyData;private final UsuarioRepository users;
 private final LocalFileStorageService storage;private final SupplierCreditNotePdfService creditPdf;
 public SupplierCreditNoteService(SupplierCreditNoteRepository notes,SupplierCreditNoteLineRepository noteLines,SupplierCreditApplicationRepository applications,SupplierRepository suppliers,PurchaseInvoiceRepository invoices,AccountsPayableRepository payables,MonedaRepository currencies,TasaCambioRepository exchangeRates,ImpuestoRepository taxes,ProductRepository products,PurchaseOrderCalculationService calculations,SupplierCreditNoteNumberService numbers,SupplierCreditNoteMapper mapper,AuditoriaService audit,EmpresaRepository companies,DatosEmpresaRepository companyData,UsuarioRepository users,LocalFileStorageService storage,SupplierCreditNotePdfService creditPdf){this.notes=notes;this.noteLines=noteLines;this.applications=applications;this.suppliers=suppliers;this.invoices=invoices;this.payables=payables;this.currencies=currencies;this.exchangeRates=exchangeRates;this.taxes=taxes;this.products=products;this.calculations=calculations;this.numbers=numbers;this.mapper=mapper;this.audit=audit;this.companies=companies;this.companyData=companyData;this.users=users;this.storage=storage;this.creditPdf=creditPdf;}

 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.ver')")
 public Page<NotaCreditoProveedorDto> search(String q,UUID supplier,EstadoNotaCreditoProveedor status,LocalDate from,LocalDate to,int page,int size){if(page<0||!SIZES.contains(size))throw new ReglaNegocioException("Paginación inválida.");if(from!=null&&to!=null&&to.isBefore(from))throw new ReglaNegocioException("La fecha final no puede ser anterior a la inicial.");var p=TenantContext.principalActual();return notes.buscar(p.tenantId(),p.empresaId(),clean(q),supplier,status,from,to,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"fecha","numero"))).map(n->map(n,false));}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.ver')")
 public NotaCreditoProveedorDto get(UUID id){return map(safe(id),true);}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.ver') and hasAuthority('notas_credito_proveedores.imprimir')")
 public byte[] pdf(UUID id){
  NotaCreditoProveedor note=safe(id);var principal=TenantContext.principalActual();
  Empresa company=companies.findByIdAndTenantId(note.getEmpresaId(),note.getTenantId()).orElseThrow(()->new ReglaNegocioException("No fue posible identificar la empresa de la nota."));
  DatosEmpresa data=companyData.findByEmpresaId(note.getEmpresaId()).orElse(null);
  Usuario user=users.findByIdAndTenantId(principal.usuarioId(),principal.tenantId()).orElseThrow(()->new ReglaNegocioException("No fue posible identificar al usuario que genera el documento."));
  byte[] logo=company.getLogoObjectKey()==null?null:storage.load(company.getLogoObjectKey(),5L*1024*1024).orElse(null);
  return creditPdf.generate(reportData(note,company,data,user,logo));
 }
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAnyAuthority('notas_credito_proveedores.crear','notas_credito_proveedores.editar')")
 public NotaCreditoProveedorCatalogosDto catalogs(){var p=TenantContext.principalActual();var ps=suppliers.buscar(p.tenantId(),p.empresaId(),"","",true,PageRequest.of(0,100,Sort.by("nombreComercial"))).stream().map(x->new NotaCreditoProveedorCatalogosDto.Opcion(x.getId(),x.getNombreComercial())).toList();var ms=currencies.findAllByEmpresaIdAndActivoTrueOrderByCodigoIso(p.empresaId()).stream().map(x->new NotaCreditoProveedorCatalogosDto.Opcion(x.getId(),x.getCodigoIso()+" · "+x.getNombre())).toList();UUID base=currencies.findByEmpresaIdAndMonedaBaseTrue(p.empresaId()).filter(Moneda::isActivo).map(Moneda::getId).orElse(null);return new NotaCreditoProveedorCatalogosDto(ps,ms,base);}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAnyAuthority('notas_credito_proveedores.crear','notas_credito_proveedores.editar','notas_credito_proveedores.aplicar')")
 public List<FacturaAplicacionCreditoDto> searchInvoices(UUID supplier,UUID currency,String q,int offset,int limit){if(supplier==null||currency==null||offset<0||limit<1||limit>50)return List.of();var p=TenantContext.principalActual();return invoices.buscarParaNotaCredito(p.tenantId(),p.empresaId(),supplier,currency,clean(q),PageRequest.of(offset/limit,limit,Sort.by("vencimiento","fecha","numeroInterno"))).stream().map(this::invoiceOption).toList();}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.aplicar')")
 public Page<FacturaAplicacionCreditoDto> searchPendingInvoices(UUID noteId,String q,int page,int size){if(page<0||!Set.of(5,10,25,50).contains(size))throw new ReglaNegocioException("Paginación inválida.");NotaCreditoProveedor n=safe(noteId);var p=TenantContext.principalActual();return invoices.buscarPendientesParaAplicar(p.tenantId(),p.empresaId(),n.getProveedorId(),n.getMonedaId(),clean(q),PageRequest.of(page,size,Sort.by("vencimiento","fecha","numeroInterno"))).map(this::invoiceOption);}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.aplicar')")
 public List<AplicarCreditoProveedorInput.Aplicacion> proposeApplications(UUID noteId){NotaCreditoProveedor n=safe(noteId);BigDecimal remaining=n.disponible();if(remaining.signum()<=0)return List.of();List<AplicarCreditoProveedorInput.Aplicacion> result=new ArrayList<>();for(CuentaPagar payable:payables.pendientes(n.getTenantId(),n.getEmpresaId(),n.getProveedorId(),n.getMonedaId())){if(remaining.signum()<=0)break;BigDecimal amount=payable.saldo().min(remaining);if(amount.signum()>0){result.add(new AplicarCreditoProveedorInput.Aplicacion(payable.getFacturaId(),amount));remaining=remaining.subtract(amount);}}return result;}
 @Transactional(readOnly=true) @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAnyAuthority('notas_credito_proveedores.crear','notas_credito_proveedores.editar')")
 public List<LineaFacturaParaCreditoDto> invoiceLines(UUID invoiceId){FacturaProveedor f=invoice(invoiceId);var p=TenantContext.principalActual();return f.getLineas().stream().map(l->{BigDecimal used=noteLines.cantidadAcreditada(p.tenantId(),p.empresaId(),l.getId());return new LineaFacturaParaCreditoDto(l.getId(),l.getProductoId(),l.getProductoCodigo(),l.getDescripcion(),l.getUnidad(),l.getCantidad(),used,l.getCantidad().subtract(used).max(BigDecimal.ZERO),l.getPrecio(),l.getDescuento(),l.getImpuestoId(),l.getImpuestoNombre(),l.getImpuestoTasa());}).toList();}
 @Transactional(readOnly=true) public List<OrdenCompraCatalogosDto.ImpuestoOpcion> taxOptions(){var p=TenantContext.principalActual();return taxes.findAllByTenantIdAndEmpresaIdAndActivoTrueOrderByNombre(p.tenantId(),p.empresaId()).stream().map(t->new OrdenCompraCatalogosDto.ImpuestoOpcion(t.getId(),t.getNombre(),t.getPorcentaje())).toList();}

 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.crear')")
 public NotaCreditoProveedorDto create(NotaCreditoProveedorInput input){var p=TenantContext.principalActual();Validated v=validate(input,null);NotaCreditoProveedor n=new NotaCreditoProveedor(p.tenantId(),p.empresaId(),numbers.next(p.tenantId(),p.empresaId()),v.supplier().getId(),v.invoice()==null?null:v.invoice().getId(),input.fecha(),required(input.numeroProveedor(),100,"El número de nota del proveedor es obligatorio."),v.normalized(),optional(input.numeroFiscal(),50),v.currency().getId(),v.rate(),input.motivo(),v.otherReason(),optional(input.observacion(),1000),p.usuarioId());applyLines(n,v,p);n=notes.saveAndFlush(n);audit.registrar("SUPPLIER_CREDIT_NOTE_CREATED","NotaCreditoProveedor",n.getId(),detail(n));return map(n,true);}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.crear') and hasAuthority('notas_credito_proveedores.confirmar')")
 public NotaCreditoProveedorDto createAndConfirm(NotaCreditoProveedorInput input){NotaCreditoProveedorDto created=create(input);return confirm(created.id(),created.version());}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.editar')")
 public NotaCreditoProveedorDto update(UUID id,NotaCreditoProveedorInput input){NotaCreditoProveedor n=locked(id);draft(n);expected(n,input==null?null:input.version());var p=TenantContext.principalActual();Validated v=validate(input,id);n.reemplazarLineas(List.of());notes.flush();n.actualizar(v.supplier().getId(),v.invoice()==null?null:v.invoice().getId(),input.fecha(),required(input.numeroProveedor(),100,"El número de nota del proveedor es obligatorio."),v.normalized(),optional(input.numeroFiscal(),50),v.currency().getId(),v.rate(),input.motivo(),v.otherReason(),optional(input.observacion(),1000),p.usuarioId());applyLines(n,v,p);n=notes.saveAndFlush(n);audit.registrar("SUPPLIER_CREDIT_NOTE_UPDATED","NotaCreditoProveedor",n.getId(),detail(n));return map(n,true);}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.editar') and hasAuthority('notas_credito_proveedores.confirmar')")
 public NotaCreditoProveedorDto updateAndConfirm(UUID id,NotaCreditoProveedorInput input){NotaCreditoProveedorDto updated=update(id,input);return confirm(id,updated.version());}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.confirmar')")
 public NotaCreditoProveedorDto confirm(UUID id,long version){NotaCreditoProveedor n=locked(id);if(n.getEstado()!=EstadoNotaCreditoProveedor.DRAFT)return map(n,true);expected(n,version);validateStoredLimits(n);var p=TenantContext.principalActual();n.confirmar(p.usuarioId());notes.saveAndFlush(n);if(n.getFacturaRelacionadaId()!=null){CuentaPagar payable=payables.bloquearPorFactura(n.getFacturaRelacionadaId(),n.getTenantId(),n.getEmpresaId()).filter(c->!c.isAnulada()).orElse(null);if(payable!=null&&payable.saldo().signum()>0)applyOne(n,payable,n.disponible().min(payable.saldo()),p.usuarioId());}audit.registrar("SUPPLIER_CREDIT_NOTE_CONFIRMED","NotaCreditoProveedor",n.getId(),detail(n));return map(n,true);}
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.aplicar')")
 public NotaCreditoProveedorDto apply(UUID id,AplicarCreditoProveedorInput input){
  NotaCreditoProveedor n=locked(id);expected(n,input==null?null:input.version());
  if(n.getEstado()==EstadoNotaCreditoProveedor.DRAFT||n.getEstado()==EstadoNotaCreditoProveedor.VOIDED||n.disponible().signum()<=0)throw new ReglaNegocioException("La nota no tiene crédito disponible.");
  if(input.aplicaciones()==null||input.aplicaciones().isEmpty())throw new ReglaNegocioException("Selecciona al menos una factura e importe.");
  List<AplicarCreditoProveedorInput.Aplicacion> requested=new ArrayList<>(input.aplicaciones());requested.sort(Comparator.comparing(AplicarCreditoProveedorInput.Aplicacion::facturaId));
  Set<UUID> unique=new HashSet<>();var p=TenantContext.principalActual();
  for(var application:requested){
   if(application==null||application.facturaId()==null||application.monto()==null||application.monto().signum()<=0)throw new ReglaNegocioException("Los importes a aplicar deben ser mayores que cero.");
   if(!unique.add(application.facturaId()))throw new ReglaNegocioException("La factura está repetida en la aplicación.");
   CuentaPagar payable=payables.bloquearPorFactura(application.facturaId(),p.tenantId(),p.empresaId()).orElseThrow(()->new ReglaNegocioException("La factura ya no tiene una cuenta por pagar disponible."));
   if(!payable.getProveedorId().equals(n.getProveedorId()))throw new ReglaNegocioException("El crédito solo puede aplicarse a facturas del mismo proveedor.");
   if(!payable.getMonedaId().equals(n.getMonedaId()))throw new ReglaNegocioException("La factura debe tener la misma moneda de la nota de crédito.");
   if(application.monto().compareTo(payable.saldo())>0)throw new ReglaNegocioException("El saldo de una factura cambió. El saldo pendiente actual es "+payable.saldo().setScale(2,RoundingMode.HALF_UP)+".");
   if(application.monto().compareTo(n.disponible())>0)throw new ReglaNegocioException("El crédito disponible cambió o el total propuesto lo supera. Actualiza la pantalla.");
   applyOne(n,payable,application.monto(),p.usuarioId());
  }
  audit.registrar("SUPPLIER_CREDIT_APPLIED","NotaCreditoProveedor",n.getId(),detail(n));return map(n,true);
 }
 @Transactional @PreAuthorize("@empresaModuloService.habilitado('COMPRAS') and hasAuthority('notas_credito_proveedores.anular')")
 public NotaCreditoProveedorDto voidNote(UUID id,long version,String reason){NotaCreditoProveedor n=locked(id);if(n.getEstado()==EstadoNotaCreditoProveedor.VOIDED)return map(n,true);expected(n,version);String r=required(reason,500,"El motivo de anulación es obligatorio.");var p=TenantContext.principalActual();for(var a:applications.findAllByNotaIdAndTenantIdAndEmpresaIdAndReversedFalseOrderByAplicadaEn(n.getId(),n.getTenantId(),n.getEmpresaId())){CuentaPagar payable=payables.bloquearPorFactura(a.getFacturaId(),n.getTenantId(),n.getEmpresaId()).orElseThrow(()->new ReglaNegocioException("No se pudo revertir una aplicación de la nota."));payable.revertirCredito(a.getMonto());payables.save(payable);FacturaProveedor f=invoices.bloquear(a.getFacturaId(),n.getTenantId(),n.getEmpresaId()).orElseThrow();f.actualizarEstadoFinanciero(payable.getEstado(),p.usuarioId());a.revertir(r,p.usuarioId());applications.save(a);n.revertir(a.getMonto(),p.usuarioId());}n.anular(r,p.usuarioId());notes.saveAndFlush(n);audit.registrar("SUPPLIER_CREDIT_NOTE_VOIDED","NotaCreditoProveedor",n.getId(),detail(n));return map(n,true);}

 private Validated validate(NotaCreditoProveedorInput i,UUID current){
  if(i==null)throw new ReglaNegocioException("Los datos de la nota de crédito son obligatorios.");
  var p=TenantContext.principalActual();
  Proveedor supplier=suppliers.findByIdAndTenantIdAndEmpresaId(i.proveedorId(),p.tenantId(),p.empresaId()).filter(Proveedor::isActivo).orElseThrow(()->new ReglaNegocioException("El proveedor seleccionado no está disponible."));
  if(i.fecha()==null)throw new ReglaNegocioException("La fecha es obligatoria.");
  Moneda currency=currencies.findByIdAndEmpresaId(i.monedaId(),p.empresaId()).filter(Moneda::isActivo).orElseThrow(()->new ReglaNegocioException("La moneda no está disponible."));
  String number=required(i.numeroProveedor(),100,"El número de nota del proveedor es obligatorio.");String normalized=normalize(number);
  boolean duplicate=current==null?notes.existsByTenantIdAndEmpresaIdAndProveedorIdAndNumeroProveedorNormalizado(p.tenantId(),p.empresaId(),supplier.getId(),normalized):notes.existsByTenantIdAndEmpresaIdAndProveedorIdAndNumeroProveedorNormalizadoAndIdNot(p.tenantId(),p.empresaId(),supplier.getId(),normalized,current);
  if(duplicate)throw new ReglaNegocioException("Ya existe una nota de crédito con ese número para el proveedor.");
  if(i.motivo()==null)throw new ReglaNegocioException("El motivo es obligatorio.");
  String other=i.motivo()==MotivoNotaCreditoProveedor.OTHER?required(i.otroMotivo(),250,"Especifica el motivo de la nota de crédito."):optional(i.otroMotivo(),250);
  FacturaProveedor invoice=i.facturaRelacionadaId()==null?null:invoice(i.facturaRelacionadaId());
  if(invoice!=null&&(!invoice.getProveedorId().equals(supplier.getId())||!invoice.getMonedaId().equals(currency.getId())))throw new ReglaNegocioException("La factura debe pertenecer al proveedor y utilizar la misma moneda.");
  Moneda base=currencies.findByEmpresaIdAndMonedaBaseTrue(p.empresaId()).orElseThrow(()->new ReglaNegocioException("Configura la moneda base de la empresa."));
  BigDecimal rate=resolveRate(p,currency,base,i.fecha());
  if(i.lineas()==null||i.lineas().isEmpty())throw new ReglaNegocioException("Agrega al menos una línea a la nota de crédito.");
  List<ValidLine> lines=new ArrayList<>();Set<UUID> usedInvoiceLines=new HashSet<>();
  for(var l:i.lineas()){
   LineaFacturaProveedor original=null;
   if(l.lineaFacturaId()!=null){
    if(invoice==null)throw new ReglaNegocioException("Una línea de factura requiere una factura relacionada.");
    original=invoice.getLineas().stream().filter(x->x.getId().equals(l.lineaFacturaId())).findFirst().orElseThrow(()->new ReglaNegocioException("La línea no pertenece a la factura relacionada."));
    if(!usedInvoiceLines.add(original.getId()))throw new ReglaNegocioException("La línea de factura está repetida.");
    BigDecimal already=noteLines.cantidadAcreditada(p.tenantId(),p.empresaId(),original.getId());
    if(l.cantidad()==null||l.cantidad().compareTo(original.getCantidad().subtract(already))>0)throw new ReglaNegocioException("La cantidad acreditada supera la cantidad disponible de la factura.");
    if(!Objects.equals(original.getProductoId(),l.productoId()))throw new ReglaNegocioException("El producto no corresponde a la línea de la factura.");
   }
   Producto product=l.productoId()==null?null:products.findByIdAndTenantIdAndEmpresaId(l.productoId(),p.tenantId(),p.empresaId()).filter(Producto::isActivo).orElseThrow(()->new ReglaNegocioException("El producto seleccionado no está disponible."));
   Impuesto tax=l.impuestoId()==null?null:taxes.findByIdAndTenantIdAndEmpresaId(l.impuestoId(),p.tenantId(),p.empresaId()).filter(Impuesto::isActivo).orElseThrow(()->new ReglaNegocioException("El impuesto seleccionado no está disponible."));
   var c=calculations.calculate(new LineaOrdenCompraInput(l.productoId(),l.descripcion(),l.cantidad(),l.precioUnitario(),l.descuento(),l.impuestoId()),tax==null?null:tax.getNombre(),tax==null?BigDecimal.ZERO:tax.getPorcentaje());lines.add(new ValidLine(original,product,tax,c));
  }
  var totals=calculations.totals(lines.stream().map(ValidLine::calculated).toList());if(totals.total().signum()<=0)throw new ReglaNegocioException("El total de la nota de crédito debe ser mayor que cero.");
  return new Validated(supplier,currency,invoice,normalized,rate,other,lines,totals);
 }
 private BigDecimal resolveRate(TenantPrincipal principal,Moneda currency,Moneda base,LocalDate date){
  if(currency.getId().equals(base.getId()))return null;
  return exchangeRates.findByTenantIdAndEmpresaIdAndMonedaOrigenIdAndMonedaDestinoIdAndFechaAndActivoTrue(principal.tenantId(),principal.empresaId(),currency.getId(),base.getId(),date)
      .map(TasaCambio::getTasa)
      .or(()->exchangeRates.findByTenantIdAndEmpresaIdAndMonedaOrigenIdAndMonedaDestinoIdAndFechaAndActivoTrue(principal.tenantId(),principal.empresaId(),base.getId(),currency.getId(),date)
          .map(rate->BigDecimal.ONE.divide(rate.getTasa(),8,RoundingMode.HALF_UP)))
      .orElseThrow(()->new ReglaNegocioException("No existe una tasa de cambio disponible para la fecha y moneda seleccionadas."));
 }
 private void applyLines(NotaCreditoProveedor n,Validated v,TenantPrincipal p){List<LineaNotaCreditoProveedor> result=new ArrayList<>();int order=1;for(var x:v.lines()){var c=x.calculated();LineaFacturaProveedor o=x.original();Producto product=x.product();result.add(new LineaNotaCreditoProveedor(p.tenantId(),p.empresaId(),o==null?null:o.getId(),product!=null?product.getId():o==null?null:o.getProductoId(),product!=null?product.getCodigo():o==null?null:o.getProductoCodigo(),c.description(),product!=null&&product.getUnidadMedida()!=null?product.getUnidadMedida().getNombre():o==null?null:o.getUnidad(),o==null?null:o.getCantidad(),c.quantity(),c.unitPrice(),c.discount(),x.tax()==null?null:x.tax().getId(),c.taxName(),c.taxRate(),c.taxAmount(),c.grossSubtotal(),c.total(),order++));}n.reemplazarLineas(result);n.totales(v.totals().subtotal(),v.totals().discount(),v.totals().tax(),v.totals().total());}
 private void applyOne(NotaCreditoProveedor n,CuentaPagar payable,BigDecimal amount,UUID user){if(amount.signum()<=0)return;payable.aplicarCredito(amount);payables.save(payable);FacturaProveedor f=invoices.bloquear(payable.getFacturaId(),n.getTenantId(),n.getEmpresaId()).orElseThrow(()->new ReglaNegocioException("Factura no encontrada."));f.actualizarEstadoFinanciero(payable.getEstado(),user);applications.saveAndFlush(new AplicacionNotaCreditoProveedor(n.getTenantId(),n.getEmpresaId(),n.getId(),payable.getFacturaId(),payable.getId(),amount,user));n.aplicar(amount,user);notes.save(n);audit.registrar("SUPPLIER_CREDIT_APPLICATION_CREATED","AplicacionNotaCreditoProveedor",n.getId(),"{\"facturaId\":\""+payable.getFacturaId()+"\",\"monto\":"+amount+"}");}
 private void validateStoredLimits(NotaCreditoProveedor n){for(var l:n.getLineas())if(l.getLineaFacturaId()!=null){BigDecimal already=noteLines.cantidadAcreditada(n.getTenantId(),n.getEmpresaId(),l.getLineaFacturaId());if(l.getCantidadFacturada()==null||l.getCantidad().compareTo(l.getCantidadFacturada().subtract(already))>0)throw new ReglaNegocioException("Otra nota de crédito consumió la cantidad disponible de una línea. Actualiza el documento.");}}
 private SupplierCreditNoteReportData reportData(NotaCreditoProveedor note,Empresa company,DatosEmpresa data,Usuario user,byte[] logo){
  List<SupplierCreditNoteReportLine> lines=new ArrayList<>();int number=1;
  Map<String,BigDecimal> taxTotals=new LinkedHashMap<>();
  for(LineaNotaCreditoProveedor line:note.getLineas()){
   lines.add(new SupplierCreditNoteReportLine(number++,line.getDescripcion(),line.getCantidad(),line.getPrecio(),line.getImpuesto(),line.getTotal()));
   if(line.getImpuesto()!=null&&line.getImpuesto().signum()>0)taxTotals.merge(value(line.getImpuestoNombre(),"Impuestos"),line.getImpuesto(),BigDecimal::add);
  }
  List<SupplierCreditTaxReportLine> taxesReport=taxTotals.entrySet().stream().map(x->new SupplierCreditTaxReportLine(x.getKey(),x.getValue())).toList();
  List<SupplierCreditApplicationReportLine> applicationReport=applications.findAllByNotaIdAndTenantIdAndEmpresaIdAndReversedFalseOrderByAplicadaEn(note.getId(),note.getTenantId(),note.getEmpresaId()).stream().map(a->{
   FacturaProveedor invoice=invoices.findByIdAndTenantIdAndEmpresaId(a.getFacturaId(),note.getTenantId(),note.getEmpresaId()).orElse(null);
   return new SupplierCreditApplicationReportLine(a.getAplicadaEn()==null?"—":DateTimeFormatter.ofPattern("dd/MM/yyyy").format(a.getAplicadaEn()),invoice==null?"—":value(invoice.getNumeroInterno(),"—"),invoice==null?"—":value(invoice.getNumeroProveedor(),"—"),a.getMonto());
  }).toList();
  String related=note.getFacturaRelacionada()==null?"—":value(note.getFacturaRelacionada().getNumeroInterno(),"—")+" / "+value(note.getFacturaRelacionada().getNumeroProveedor(),"—");
  String commercial=data==null?company.getNombre():value(data.getNombreComercial(),company.getNombre());
  String legal=data==null?company.getNombre():value(data.getRazonSocial(),company.getNombre());
  return new SupplierCreditNoteReportData(note.getTenantId(),note.getEmpresaId(),note.getId(),note.getNumero(),commercial,legal,company.getIdentificacionFiscal(),data==null?null:data.getDireccion(),data==null?null:data.getTelefono(),data==null?null:data.getCorreo(),logo,note.getProveedor()==null?null:note.getProveedor().getNombreComercial(),note.getProveedor()==null?null:note.getProveedor().getIdentificacionFiscal(),note.getFecha(),stateLabel(note.getEstado()),note.getNumeroProveedor(),note.getNumeroFiscal(),note.getMoneda()==null?null:note.getMoneda().getCodigoIso(),reasonLabel(note),related,note.getNotas(),note.getSubtotal(),note.getDescuento(),note.getImpuesto(),note.getTotal(),note.getAplicado(),note.disponible(),PurchaseOrderService.issuedByDisplayName(user),OffsetDateTime.now(),lines,taxesReport,applicationReport);
 }
 private static String stateLabel(EstadoNotaCreditoProveedor state){return switch(state){case DRAFT->"BORRADOR";case AVAILABLE->"DISPONIBLE";case PARTIALLY_APPLIED->"PARCIALMENTE APLICADA";case APPLIED->"APLICADA";case VOIDED->"ANULADA";};}
 private static String reasonLabel(NotaCreditoProveedor note){if(note.getMotivo()==MotivoNotaCreditoProveedor.OTHER)return value(note.getOtroMotivo(),"Otro");return switch(note.getMotivo()){case GOODS_RETURN->"Devolución de mercancía";case POST_PURCHASE_DISCOUNT->"Descuento posterior a la compra";case PRICE_DIFFERENCE->"Diferencia de precio";case BONUS->"Bonificación";case INVOICE_CORRECTION->"Corrección de factura";case DEFECTIVE_GOODS->"Mercancía defectuosa";case OTHER->"Otro";};}
 private static String value(String value,String fallback){return value==null||value.isBlank()?fallback:value.trim();}
 private NotaCreditoProveedorDto map(NotaCreditoProveedor n,boolean detail){BigDecimal balance=n.getFacturaRelacionadaId()==null?null:payables.findByFacturaIdAndTenantIdAndEmpresaId(n.getFacturaRelacionadaId(),n.getTenantId(),n.getEmpresaId()).map(CuentaPagar::saldo).orElse(BigDecimal.ZERO);List<AplicacionNotaCreditoProveedorDto> apps=detail?applications.findAllByNotaIdAndTenantIdAndEmpresaIdAndReversedFalseOrderByAplicadaEn(n.getId(),n.getTenantId(),n.getEmpresaId()).stream().map(a->{FacturaProveedor invoice=invoices.findByIdAndTenantIdAndEmpresaId(a.getFacturaId(),n.getTenantId(),n.getEmpresaId()).orElse(null);return new AplicacionNotaCreditoProveedorDto(a.getId(),a.getFacturaId(),invoice==null?"—":invoice.getNumeroInterno(),invoice==null?"—":invoice.getNumeroProveedor(),a.getAplicadaEn(),a.getMonto());}).toList():List.of();return mapper.toDto(n,balance,apps,detail);}
 private FacturaAplicacionCreditoDto invoiceOption(FacturaProveedor f){CuentaPagar c=payables.findByFacturaIdAndTenantIdAndEmpresaId(f.getId(),f.getTenantId(),f.getEmpresaId()).orElse(null);BigDecimal credits=applications.totalAplicadoFactura(f.getTenantId(),f.getEmpresaId(),f.getId());return new FacturaAplicacionCreditoDto(f.getId(),f.getNumeroInterno(),f.getNumeroProveedor(),f.getNumeroFiscal(),f.getFecha(),f.getVencimiento(),f.getMonedaId(),f.getMoneda()==null?null:f.getMoneda().getCodigoIso(),f.getTotal(),c==null?f.getTotal():c.getMontoAplicado(),credits,c==null?BigDecimal.ZERO:c.saldo());}
 private NotaCreditoProveedor safe(UUID id){var p=TenantContext.principalActual();return notes.findByIdAndTenantIdAndEmpresaId(id,p.tenantId(),p.empresaId()).orElseThrow(()->new RecursoNoEncontradoException("Nota de crédito no encontrada."));}private NotaCreditoProveedor locked(UUID id){var p=TenantContext.principalActual();return notes.bloquear(id,p.tenantId(),p.empresaId()).orElseThrow(()->new RecursoNoEncontradoException("Nota de crédito no encontrada."));}private FacturaProveedor invoice(UUID id){var p=TenantContext.principalActual();return invoices.findByIdAndTenantIdAndEmpresaId(id,p.tenantId(),p.empresaId()).filter(f->f.getEstado()==EstadoFacturaProveedor.REGISTERED).orElseThrow(()->new ReglaNegocioException("La factura relacionada no está disponible."));}
 private static void draft(NotaCreditoProveedor n){if(n.getEstado()!=EstadoNotaCreditoProveedor.DRAFT)throw new ReglaNegocioException("Solo se pueden editar notas de crédito en borrador.");}private static void expected(NotaCreditoProveedor n,Long v){if(v==null||n.getVersion()!=v)throw new ReglaNegocioException("La nota fue modificada por otro usuario. Actualiza la pantalla.");}private static String clean(String s){return s==null?"":s.trim();}private static String required(String s,int max,String msg){String v=clean(s);if(v.isEmpty())throw new ReglaNegocioException(msg);if(v.length()>max)throw new ReglaNegocioException("El valor excede "+max+" caracteres.");return v;}private static String optional(String s,int max){String v=clean(s);if(v.isEmpty())return null;if(v.length()>max)throw new ReglaNegocioException("El valor excede "+max+" caracteres.");return v;}private static String normalize(String s){String n=Normalizer.normalize(clean(s),Normalizer.Form.NFD).replaceAll("\\p{M}","");return n.replaceAll("[^A-Za-z0-9]","").toUpperCase(Locale.ROOT);}private static String detail(NotaCreditoProveedor n){return "{\"numero\":\""+n.getNumero()+"\",\"estado\":\""+n.getEstado()+"\",\"total\":"+n.getTotal()+",\"aplicado\":"+n.getAplicado()+"}";}
 private record ValidLine(LineaFacturaProveedor original,Producto product,Impuesto tax,PurchaseOrderCalculationService.CalculatedLine calculated){}private record Validated(Proveedor supplier,Moneda currency,FacturaProveedor invoice,String normalized,BigDecimal rate,String otherReason,List<ValidLine> lines,PurchaseOrderCalculationService.Totals totals){}
}
