package com.citacloud.springboot.contacloud.app.services;
import com.citacloud.springboot.contacloud.app.models.*;import com.citacloud.springboot.contacloud.app.repositories.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.LocalDate;import java.util.UUID;import static org.assertj.core.api.Assertions.*;
class SupplierCreditNoteDomainTest{
 private final UUID tenant=UUID.randomUUID(),company=UUID.randomUUID(),supplier=UUID.randomUUID(),currency=UUID.randomUUID(),user=UUID.randomUUID();
 @Test void estadoSeDerivaDelCreditoAplicado(){NotaCreditoProveedor n=note("2500");n.confirmar(user);assertThat(n.getEstado()).isEqualTo(EstadoNotaCreditoProveedor.AVAILABLE);assertThat(n.disponible()).isEqualByComparingTo("2500");n.aplicar(new BigDecimal("1000"),user);assertThat(n.getEstado()).isEqualTo(EstadoNotaCreditoProveedor.PARTIALLY_APPLIED);assertThat(n.disponible()).isEqualByComparingTo("1500");n.aplicar(new BigDecimal("1500"),user);assertThat(n.getEstado()).isEqualTo(EstadoNotaCreditoProveedor.APPLIED);assertThat(n.disponible()).isZero();}
 @Test void cuentaPorPagarNuncaAdmiteCreditoMayorAlSaldo(){CuentaPagar c=new CuentaPagar(tenant,company,UUID.randomUUID(),supplier,currency,LocalDate.now(),new BigDecimal("1000"),user);c.aplicarCredito(new BigDecimal("750"));assertThat(c.saldo()).isEqualByComparingTo("250");assertThat(c.getEstado()).isEqualTo(EstadoCuentaPagar.PARTIALLY_PAID);assertThatThrownBy(()->c.aplicarCredito(new BigDecimal("251"))).isInstanceOf(IllegalArgumentException.class);c.aplicarCredito(new BigDecimal("250"));assertThat(c.saldo()).isZero();assertThat(c.getEstado()).isEqualTo(EstadoCuentaPagar.PAID);}
 @Test void reversionRestauraCreditoYCuentaPorPagar(){NotaCreditoProveedor n=note("2500");n.confirmar(user);n.aplicar(new BigDecimal("1000"),user);CuentaPagar c=new CuentaPagar(tenant,company,UUID.randomUUID(),supplier,currency,LocalDate.now(),new BigDecimal("5000"),user);c.aplicarCredito(new BigDecimal("1000"));n.revertir(new BigDecimal("1000"),user);c.revertirCredito(new BigDecimal("1000"));assertThat(n.getEstado()).isEqualTo(EstadoNotaCreditoProveedor.AVAILABLE);assertThat(n.disponible()).isEqualByComparingTo("2500");assertThat(c.saldo()).isEqualByComparingTo("5000");}
 @Test void permiteAgotarElCreditoEnVariasFacturas(){NotaCreditoProveedor n=note("2950.00");n.confirmar(user);BigDecimal primera=new BigDecimal("11.80");assertThat(primera).isLessThanOrEqualTo(n.disponible());n.aplicar(primera,user);BigDecimal segunda=new BigDecimal("2938.20");assertThat(segunda).isLessThanOrEqualTo(n.disponible());n.aplicar(segunda,user);assertThat(n.getAplicado()).isEqualByComparingTo("2950.00");assertThat(n.disponible()).isZero();assertThat(n.getEstado()).isEqualTo(EstadoNotaCreditoProveedor.APPLIED);}
 @Test void servicioNoDependeDeMovimientosDeInventarioNiFinancieros(){assertThat(java.util.Arrays.stream(SupplierCreditNoteService.class.getDeclaredFields()).map(f->f.getType().getName())).doesNotContain(InventoryMovementRepository.class.getName(),InventoryMovementService.class.getName(),FinancialMovementRepository.class.getName());}
 private NotaCreditoProveedor note(String total){NotaCreditoProveedor n=new NotaCreditoProveedor(tenant,company,"NC-000001",supplier,null,LocalDate.now(),"NC-P-1","NCP1",null,currency,null,MotivoNotaCreditoProveedor.PRICE_DIFFERENCE,null,null,user);n.totales(new BigDecimal(total),BigDecimal.ZERO,BigDecimal.ZERO,new BigDecimal(total));return n;}
}
