package com.citacloud.springboot.contacloud.app.services;
import com.citacloud.springboot.contacloud.app.models.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.LocalDate;import java.util.UUID;import static org.assertj.core.api.Assertions.*;
class SupplierPaymentDomainTest{
 private final UUID tenant=UUID.randomUUID(),company=UUID.randomUUID(),supplier=UUID.randomUUID(),currency=UUID.randomUUID(),account=UUID.randomUUID(),user=UUID.randomUUID();
 @Test void anticipoConfirmadoQuedaDisponible(){PagoProveedor p=payment("10000");assertThat(p.getEstado()).isEqualTo(EstadoPagoProveedor.DRAFT);p.confirmar(user);assertThat(p.getEstado()).isEqualTo(EstadoPagoProveedor.AVAILABLE);assertThat(p.disponible()).isEqualByComparingTo("10000");}
 @Test void aplicacionesActualizanEstadoSinCrearOtroPago(){PagoProveedor p=payment("10000");p.confirmar(user);p.aplicar(new BigDecimal("6755.84"),user);assertThat(p.getEstado()).isEqualTo(EstadoPagoProveedor.PARTIALLY_APPLIED);assertThat(p.disponible()).isEqualByComparingTo("3244.16");p.aplicar(new BigDecimal("3244.16"),user);assertThat(p.getEstado()).isEqualTo(EstadoPagoProveedor.APPLIED);assertThat(p.disponible()).isZero();}
 @Test void nuncaPermiteAplicarMasQueElDisponible(){PagoProveedor p=payment("1000");p.confirmar(user);assertThatThrownBy(()->p.aplicar(new BigDecimal("1000.01"),user)).isInstanceOf(IllegalArgumentException.class);}
 @Test void reversionRestauraElDisponible(){PagoProveedor p=payment("5000");p.confirmar(user);p.aplicar(new BigDecimal("3000"),user);p.revertir(new BigDecimal("3000"),user);assertThat(p.getEstado()).isEqualTo(EstadoPagoProveedor.AVAILABLE);assertThat(p.disponible()).isEqualByComparingTo("5000");}
 @Test void aplicacionConservaFotografiaHistoricaDelSaldo(){AplicacionPagoProveedor a=new AplicacionPagoProveedor(tenant,company,UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),new BigDecimal("1500"),new BigDecimal("5000"),new BigDecimal("3500"),user);assertThat(a.getSaldoAnterior()).isEqualByComparingTo("5000");assertThat(a.getMonto()).isEqualByComparingTo("1500");assertThat(a.getSaldoRestante()).isEqualByComparingTo("3500");assertThat(a.getSaldoAnterior().subtract(a.getMonto())).isEqualByComparingTo(a.getSaldoRestante());}
 private PagoProveedor payment(String amount){return new PagoProveedor(tenant,company,"PG-000001",supplier,LocalDate.now(),currency,new BigDecimal(amount),TipoCuentaDinero.BANK_ACCOUNT,account,MedioPagoMovimiento.BANK_TRANSFER,null,"TRX",null,UUID.randomUUID(),user);}
}
