package com.citacloud.springboot.contacloud.app.views;

import com.citacloud.springboot.contacloud.app.dto.*;
import com.citacloud.springboot.contacloud.app.security.TenantContext;
import com.citacloud.springboot.contacloud.app.services.*;
import com.citacloud.springboot.contacloud.app.views.components.*;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.*;
import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;

import java.util.*;

@Route(value="categorias",layout=MainLayout.class)
@PageTitle("Categorías | ContaCloud")
@PermitAll
public class CategoriasView extends VerticalLayout implements BeforeEnterObserver,BeforeLeaveObserver {
    private final CategoryService service;private final EmpresaModuloService modules;
    private final TextField search=new TextField("Buscar");private final Select<String> state=new Select<>();
    private final AppGrid<CategoriaDto> grid=new AppGrid<>(CategoriaDto.class);private final AppPagination pagination;
    private Dialog openForm;private Dirty dirty;

    public CategoriasView(CategoryService service,EmpresaModuloService modules){this.service=service;this.modules=modules;addClassName("cc-page");setPadding(false);setSpacing(false);setWidthFull();Component create=can("categorias.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nueva categoría",e->form(null)):null;add(create==null?new AppPageHeader("CATEGORÍAS","Administra las categorías utilizadas para clasificar productos y servicios."):new AppPageHeader("CATEGORÍAS","Administra las categorías utilizadas para clasificar productos y servicios.",create));search.setPlaceholder("Buscar por nombre...");search.setClearButtonVisible(true);search.setValueChangeMode(ValueChangeMode.LAZY);search.setValueChangeTimeout(400);state.setLabel("Estado");state.setItems("Todos","Activa","Inactiva");state.setValue("Todos");search.addValueChangeListener(e->{if(e.isFromClient())reset();});state.addValueChangeListener(e->{if(e.isFromClient())reset();});HorizontalLayout filters=new HorizontalLayout(search,state);filters.addClassName("cc-filter-bar");filters.setAlignItems(Alignment.END);filters.setWidthFull();configureGrid();pagination=new AppPagination(r->load());add(filters,grid,pagination);}

    @Override public void beforeEnter(BeforeEnterEvent event){if(!modules.habilitado("INVENTARIO")||!can("categorias.ver")){Notification.show("No tienes permiso para acceder a esta opción.");event.rerouteTo(DashboardView.class);return;}load();}
    @Override public void beforeLeave(BeforeLeaveEvent event){if(openForm==null||dirty==null||!dirty.value)return;var action=event.postpone();confirmDiscard(()->{dirty.value=false;openForm.close();action.proceed();});}

    private void configureGrid(){grid.addColumn(CategoriaDto::nombre).setHeader("Nombre").setFlexGrow(1);grid.addColumn(c->display(c.descripcion())).setHeader("Descripción").setFlexGrow(2);grid.addComponentColumn(c->badge(c.activo())).setHeader("Estado").setAutoWidth(true).setFlexGrow(0);grid.addComponentColumn(this::actions).setHeader("Acciones").setAutoWidth(true).setFlexGrow(0);grid.setEmptyStateText(emptyMessage());}
    private Component actions(CategoriaDto category){HorizontalLayout actions=new HorizontalLayout();actions.addClassName("cc-grid-actions");actions.setPadding(false);actions.setSpacing(false);actions.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver categoría",e->detail(category.id())));if(can("categorias.editar"))actions.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar categoría",e->form(category.id())));return actions;}
    private void load(){grid.setEnabled(false);try{var request=pagination.currentRequest();var page=service.searchCategories(search.getValue(),stateFilter(),request.page(),request.size());grid.setItems(page.getContent());boolean filtered=!search.getValue().isBlank()||stateFilter()!=null;grid.setEmptyStateText(filtered?"No se encontraron categorías con los filtros seleccionados.":emptyMessage());pagination.setTotal(page.getTotalElements());}catch(RuntimeException ex){error(ex,"No fue posible cargar las categorías.");}finally{grid.setEnabled(true);}}
    private void reset(){pagination.reset();load();}private Boolean stateFilter(){return switch(state.getValue()==null?"Todos":state.getValue()){case"Activa"->true;case"Inactiva"->false;default->null;};}
    private String emptyMessage(){return can("categorias.crear")?"No hay categorías registradas. Crea la primera categoría para comenzar a clasificar tus productos y servicios.":"No hay categorías registradas.";}

    private void form(UUID id){try{CategoriaDto current=id==null?null:service.getCategory(id);Dialog dialog=dialog(current==null?"NUEVA CATEGORÍA":"EDITAR CATEGORÍA");TextField name=new TextField("Nombre");name.setRequiredIndicatorVisible(true);name.setMaxLength(120);TextArea description=new TextArea("Descripción");description.setMaxLength(500);description.addClassName("cc-dialog-span-2");Checkbox active=new Checkbox("Activa",true);active.addClassName("cc-dialog-span-2");if(current!=null){name.setValue(current.nombre());description.setValue(value(current.descripcion()));active.setValue(current.activo());active.setReadOnly(true);}Dirty changes=new Dirty();name.addValueChangeListener(e->changes.mark(e.isFromClient()));description.addValueChangeListener(e->changes.mark(e.isFromClient()));active.addValueChangeListener(e->changes.mark(e.isFromClient()));dialog.add(section("INFORMACIÓN GENERAL",name,description,active));AppActionButton save=new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",null);save.addClickListener(e->{save.setEnabled(false);try{CategoriaInput input=new CategoriaInput(name.getValue(),description.getValue(),active.getValue(),current==null?null:current.version());if(current==null)service.createCategory(input);else service.updateCategory(current.id(),input);changes.value=false;dialog.close();load();Notification.show(current==null?"Categoría creada correctamente.":"Categoría actualizada correctamente.");}catch(RuntimeException ex){save.setEnabled(true);error(ex,"No fue posible guardar la categoría.");}});dialog.getFooter().add(save,new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->closeForm(dialog,changes)));dialog.setCloseOnEsc(false);dialog.setCloseOnOutsideClick(false);dialog.addDialogCloseActionListener(e->closeForm(dialog,changes));openForm=dialog;dirty=changes;dialog.addClosedListener(e->{if(openForm==dialog){openForm=null;dirty=null;}});dialog.open();}catch(RuntimeException ex){error(ex,"No fue posible abrir la categoría.");}}

    private void detail(UUID id){try{CategoriaDto category=service.getCategory(id);Dialog dialog=dialog("CATEGORÍA");Div heading=new Div(new H2(category.nombre()),badge(category.activo()));heading.addClassName("cc-detail-heading");dialog.add(heading,new AppDetailSection("INFORMACIÓN GENERAL").field("Nombre",category.nombre()).field("Estado",category.activo()?"Activa":"Inactiva").field("Descripción",display(category.descripcion())).field("Productos / Servicios",Long.toString(category.productosServicios())));if(can("categorias.editar"))dialog.getFooter().add(new AppActionButton(ActionType.EDIT,ButtonSize.MAIN,"Editar categoría",e->{dialog.close();form(category.id());}));if(category.activo()&&can("categorias.desactivar"))dialog.getFooter().add(new AppActionButton(ActionType.DEACTIVATE,ButtonSize.MAIN,"Desactivar categoría",e->confirmState(category,dialog)));if(!category.activo()&&can("categorias.reactivar"))dialog.getFooter().add(new AppActionButton(ActionType.ACTIVATE,ButtonSize.MAIN,"Reactivar categoría",e->confirmState(category,dialog)));dialog.getFooter().add(new AppActionButton(ActionType.CLOSE,ButtonSize.MAIN,"Cerrar",e->dialog.close()));dialog.open();}catch(RuntimeException ex){error(ex,"No fue posible consultar la categoría.");}}
    private void confirmState(CategoriaDto category,Dialog parent){boolean deactivate=category.activo();ConfirmDialog confirm=new ConfirmDialog();confirm.setHeader(deactivate?"Desactivar categoría":"Reactivar categoría");confirm.setText(deactivate?"Los productos y servicios existentes conservarán su categoría, pero no estará disponible normalmente para nuevas asignaciones. ¿Deseas continuar?":"La categoría volverá a estar disponible para nuevas asignaciones. ¿Deseas continuar?");confirm.setCancelable(true);confirm.setCancelText("Cancelar");confirm.setConfirmText(deactivate?"Desactivar":"Reactivar");if(deactivate)confirm.setConfirmButtonTheme("error primary");confirm.addConfirmListener(e->{try{if(deactivate)service.deactivateCategory(category.id(),category.version());else service.reactivateCategory(category.id(),category.version());parent.close();load();Notification.show(deactivate?"Categoría desactivada correctamente.":"Categoría reactivada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible cambiar el estado de la categoría.");}});confirm.open();}

    private static Div section(String title,Component...fields){Div section=new Div();section.addClassName("cc-form-section");H3 heading=new H3(title);heading.addClassName("cc-section-heading");Div form=new Div(fields);form.addClassName("cc-dialog-form");section.add(heading,form);return section;}private static Dialog dialog(String title){Dialog dialog=new Dialog();dialog.setHeaderTitle(title);dialog.setWidth("min(760px, 96vw)");return dialog;}private static Span badge(boolean active){Span badge=new Span(active?"Activa":"Inactiva");badge.getElement().getThemeList().add("badge "+(active?"success":"contrast"));return badge;}private static String display(String value){return value==null||value.isBlank()?"—":value;}private static String value(String value){return value==null?"":value;}
    private static boolean can(String permission){return TenantContext.principalActual().permisos().contains(permission);}private static void closeForm(Dialog dialog,Dirty dirty){if(!dirty.value){dialog.close();return;}confirmDiscard(()->{dirty.value=false;dialog.close();});}private static void confirmDiscard(Runnable discard){ConfirmDialog confirm=new ConfirmDialog();confirm.setHeader("Cambios sin guardar");confirm.setText("Hay cambios sin guardar. ¿Deseas descartarlos?");confirm.setCancelable(true);confirm.setCancelText("Continuar editando");confirm.setConfirmText("Descartar cambios");confirm.setConfirmButtonTheme("error primary");confirm.addConfirmListener(e->discard.run());confirm.open();}private static void error(RuntimeException ex,String fallback){String message=ex instanceof ReglaNegocioException||ex instanceof RecursoNoEncontradoException?ex.getMessage():fallback;Notification.show(message==null||message.isBlank()?fallback:message);}private static final class Dirty{private boolean value;void mark(boolean client){if(client)value=true;}}
}
