package com.citacloud.springboot.contacloud.app.views;

import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.security.TenantContext;import com.citacloud.springboot.contacloud.app.services.*;import com.citacloud.springboot.contacloud.app.views.components.*;
import com.vaadin.flow.component.*;import com.vaadin.flow.component.checkbox.Checkbox;import com.vaadin.flow.component.combobox.ComboBox;import com.vaadin.flow.component.dialog.Dialog;import com.vaadin.flow.component.html.*;import com.vaadin.flow.component.notification.Notification;import com.vaadin.flow.component.orderedlayout.*;import com.vaadin.flow.component.tabs.*;import com.vaadin.flow.component.textfield.*;import com.vaadin.flow.data.value.ValueChangeMode;import com.vaadin.flow.router.*;import jakarta.annotation.security.PermitAll;
import java.math.BigDecimal;import java.math.RoundingMode;import java.util.*;

@Route(value="configuracion-fiscal",layout=MainLayout.class)
@RouteAlias(value="impuestos",layout=MainLayout.class)
@RouteAlias(value="comprobantes-fiscales",layout=MainLayout.class)
@RouteAlias(value="secuencias",layout=MainLayout.class)
@PageTitle("Configuración fiscal | ContaCloud") @PermitAll
public class ConfiguracionFiscalView extends VerticalLayout implements BeforeEnterObserver{
 private final ImpuestoFiscalService impuestos;private final ComprobanteFiscalService comprobantes;private final SecuenciaFiscalAdminService secuencias;private final EmpresaModuloService modulos;
 private final boolean verImpuestos=hasAny("impuestos.ver","IMPUESTO_VER"),verComprobantes=hasAny("comprobantes_fiscales.ver","COMPROBANTE_VER"),verSecuencias=hasAny("secuencias.ver","SECUENCIA_VER");
 private final Tab impuestoTab=new Tab("Impuestos"),comprobanteTab=new Tab("Comprobantes fiscales"),secuenciaTab=new Tab("Secuencias");private final Tabs tabs=new Tabs();private final Div contenido=new Div();private final Map<Tab,PanelFiscal> paneles=new LinkedHashMap<>();
 public ConfiguracionFiscalView(ImpuestoFiscalService i,ComprobanteFiscalService c,SecuenciaFiscalAdminService s,EmpresaModuloService m){impuestos=i;comprobantes=c;secuencias=s;modulos=m;addClassName("cc-page");setPadding(false);setSpacing(false);setWidthFull();add(new AppPageHeader("CONFIGURACIÓN FISCAL","Administra los impuestos, comprobantes fiscales y secuencias utilizadas por la empresa."));
  if(verImpuestos&&m.habilitado("IMPUESTOS")){tabs.add(impuestoTab);paneles.put(impuestoTab,new PanelImpuestos());}if(verComprobantes&&m.habilitado("COMPROBANTES_FISCALES")){tabs.add(comprobanteTab);paneles.put(comprobanteTab,new PanelComprobantes());}if(verSecuencias&&m.habilitado("SECUENCIAS")){tabs.add(secuenciaTab);paneles.put(secuenciaTab,new PanelSecuencias());}tabs.addClassName("cc-infrastructure-tabs");contenido.addClassName("cc-tab-content");add(tabs,contenido);tabs.addSelectedChangeListener(e->{if(e.isFromClient())mostrar(e.getSelectedTab(),true);});
 }
 @Override public void beforeEnter(BeforeEnterEvent e){if(paneles.isEmpty()){Notification.show("No tienes permiso para acceder a esta opción.");e.rerouteTo(DashboardView.class);return;}String path=e.getLocation().getPath();String requested=switch(path){case"comprobantes-fiscales"->"comprobantes";case"secuencias"->"secuencias";case"impuestos"->"impuestos";default->e.getLocation().getQueryParameters().getParameters().getOrDefault("tab",List.of("impuestos")).stream().findFirst().orElse("impuestos");};Tab selected=tab(requested);if(selected==null)selected=paneles.keySet().iterator().next();mostrar(selected,!"configuracion-fiscal".equals(path));}
 private Tab tab(String key){if("impuestos".equalsIgnoreCase(key)&&paneles.containsKey(impuestoTab))return impuestoTab;if("comprobantes".equalsIgnoreCase(key)&&paneles.containsKey(comprobanteTab))return comprobanteTab;if("secuencias".equalsIgnoreCase(key)&&paneles.containsKey(secuenciaTab))return secuenciaTab;return null;}
 private void mostrar(Tab tab,boolean canonical){tabs.setSelectedTab(tab);contenido.removeAll();PanelFiscal p=paneles.get(tab);contenido.add((Component)p);p.cargar();if(canonical)UI.getCurrent().getPage().getHistory().replaceState(null,"configuracion-fiscal?tab="+clave(tab));}
 private String clave(Tab t){return t==impuestoTab?"impuestos":t==comprobanteTab?"comprobantes":"secuencias";}
 private abstract class PanelFiscal extends VerticalLayout{boolean cargado;private final String titulo,descripcion;PanelFiscal(String titulo,String descripcion){this.titulo=titulo;this.descripcion=descripcion;setPadding(false);setSpacing(true);setWidthFull();}void encabezado(Component action){addComponentAsFirst(new AppPageHeader(titulo,descripcion,action==null?new Component[0]:new Component[]{action}));}abstract void cargarDatos();void cargar(){if(!cargado){cargado=true;cargarDatos();}}void recargar(){cargarDatos();}}
 private final class PanelImpuestos extends PanelFiscal{
  final TextField buscar=search("Buscar impuesto...");final ComboBox<String> estado=status();final AppGrid<ImpuestoFiscalDto> grid=new AppGrid<>(ImpuestoFiscalDto.class);final AppPagination pagination;
  PanelImpuestos(){super("IMPUESTOS","Administra los impuestos utilizados en las operaciones de la empresa.");encabezado(has("impuestos.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nuevo impuesto",e->dialog(null)):null);buscar.setPlaceholder("Buscar por nombre...");grid.addColumn(ImpuestoFiscalDto::nombre).setHeader("Nombre").setAutoWidth(true).setFlexGrow(1);grid.addColumn(x->porcentaje(x.tasa())).setHeader("Tasa").setAutoWidth(true);grid.addColumn(x->"PERCENTAGE".equals(x.tipo())?"Porcentaje":x.tipo()).setHeader("Tipo").setAutoWidth(true);grid.addComponentColumn(x->badge(x.activo()?"Activo":"Inactivo")).setHeader("Estado").setAutoWidth(true);grid.addComponentColumn(this::acciones).setHeader("Acciones").setAutoWidth(true).setFlexGrow(0);grid.setEmptyStateText("No hay impuestos registrados. Crea el primer impuesto para comenzar a configurar los impuestos de la empresa.");pagination=new AppPagination(r->recargar());buscar.addValueChangeListener(e->reset());estado.addValueChangeListener(e->reset());add(toolbar(buscar,estado),grid,pagination);}
  Component acciones(ImpuestoFiscalDto x){var a=actions();if(has("impuestos.ver"))a.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver impuesto",e->detalle(x)));if(has("impuestos.editar"))a.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar impuesto",e->dialog(x)));return a;}
  void cargarDatos(){try{var r=pagination.currentRequest();var p=impuestos.buscar(buscar.getValue(),active(estado),r.page(),r.size());grid.setItems(p.getContent());boolean filtrado=!buscar.getValue().isBlank()||active(estado)!=null;grid.setEmptyStateText(filtrado?"No se encontraron impuestos con los filtros seleccionados.":(has("impuestos.crear")?"No hay impuestos registrados. Crea el primer impuesto para comenzar a configurar los impuestos de la empresa.":"No hay impuestos registrados."));pagination.setTotal(p.getTotalElements());}catch(RuntimeException e){error(e,"No fue posible cargar la configuración fiscal.");}}
  void reset(){pagination.reset();recargar();}
  void dialog(ImpuestoFiscalDto x){boolean nuevo=x==null;var d=ConfiguracionFiscalView.dialog(nuevo?"NUEVO IMPUESTO":"EDITAR IMPUESTO");var nombre=text("Nombre",nuevo?"":x.nombre());nombre.setRequired(true);nombre.setMaxLength(120);var tasa=new BigDecimalField("Tasa");tasa.setRequired(true);tasa.setSuffixComponent(new Span("%"));tasa.addBlurListener(e->{if(tasa.getValue()!=null)tasa.setValue(tasa.getValue().setScale(2,RoundingMode.HALF_UP));});if(!nuevo)tasa.setValue(x.tasa());var tipo=new ComboBox<String>("Tipo");tipo.setItems("Porcentaje");tipo.setValue("Porcentaje");tipo.setRequired(true);tipo.setReadOnly(true);var desc=area("Descripción",nuevo?null:x.descripcion());desc.setMaxLength(500);var activo=new Checkbox("Activo",nuevo||x.activo());activo.setReadOnly(!nuevo);d.add(section("INFORMACIÓN GENERAL",nombre,tasa,tipo,desc,activo));if(nuevo||has("impuestos.editar")){AppActionButton guardar=new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",null);guardar.addClickListener(e->{guardar.setEnabled(false);try{var in=new ImpuestoFiscalInput(nombre.getValue(),tasa.getValue(),"PERCENTAGE",desc.getValue(),activo.getValue(),nuevo?null:x.version());if(nuevo)impuestos.crear(in);else impuestos.actualizar(x.id(),in);d.close();recargar();ok(nuevo?"Impuesto creado.":"Impuesto actualizado.");}catch(RuntimeException ex){guardar.setEnabled(true);error(ex,"No fue posible guardar el impuesto.");}});d.getFooter().add(guardar);}d.getFooter().add(cancel(d));d.open();}
  void detalle(ImpuestoFiscalDto x){var d=ConfiguracionFiscalView.dialog("DETALLE DEL IMPUESTO");d.add(new AppDetailSection("INFORMACIÓN GENERAL").field("Nombre",x.nombre()).field("Tasa",porcentaje(x.tasa())).field("Tipo","Porcentaje").field("Estado",x.activo()?"Activo":"Inactivo").field("Descripción",x.descripcion()));if(has("impuestos.editar"))d.getFooter().add(new AppActionButton(ActionType.EDIT,ButtonSize.MAIN,"Editar impuesto",e->{d.close();dialog(x);}));if(x.activo()&&has("impuestos.desactivar"))d.getFooter().add(state(true,e->cambiarEstado(x,d)));if(!x.activo()&&has("impuestos.reactivar"))d.getFooter().add(state(false,e->cambiarEstado(x,d)));d.getFooter().add(close(d));d.open();}
  void cambiarEstado(ImpuestoFiscalDto x,Dialog d){try{if(x.activo())impuestos.desactivar(x.id(),x.version());else impuestos.reactivar(x.id(),x.version());d.close();recargar();ok(x.activo()?"Impuesto desactivado.":"Impuesto reactivado.");}catch(RuntimeException ex){error(ex,"No fue posible cambiar el estado.");}}
 }
 private final class PanelComprobantes extends PanelFiscal{
  final TextField buscar=search("Buscar comprobante...");final ComboBox<String> estado=status();final AppGrid<ComprobanteFiscalDto> grid=new AppGrid<>(ComprobanteFiscalDto.class);final AppPagination pagination;
  PanelComprobantes(){super("COMPROBANTES FISCALES","Administra los tipos de comprobantes fiscales utilizados por la empresa.");encabezado(has("comprobantes_fiscales.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nuevo comprobante fiscal",e->dialog(null)):null);grid.addColumn(ComprobanteFiscalDto::codigo).setHeader("Código").setAutoWidth(true);grid.addColumn(ComprobanteFiscalDto::nombre).setHeader("Nombre").setAutoWidth(true).setFlexGrow(1);grid.addColumn(ComprobanteFiscalDto::prefijo).setHeader("Prefijo").setAutoWidth(true);grid.addComponentColumn(x->badge(x.activo()?"Activo":"Inactivo")).setHeader("Estado").setAutoWidth(true);grid.addComponentColumn(this::acciones).setHeader("Acciones").setAutoWidth(true).setFlexGrow(0);grid.setEmptyStateText("No hay comprobantes fiscales configurados.");pagination=new AppPagination(r->recargar());buscar.addValueChangeListener(e->reset());estado.addValueChangeListener(e->reset());add(toolbar(buscar,estado),grid,pagination);}
  Component acciones(ComprobanteFiscalDto x){var a=actions();a.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver comprobante fiscal",e->detalle(x)));if(has("comprobantes_fiscales.editar")||has("comprobantes_fiscales.desactivar"))a.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar comprobante fiscal",e->dialog(x)));return a;}
  void cargarDatos(){try{var r=pagination.currentRequest();var p=comprobantes.buscar(buscar.getValue(),active(estado),r.page(),r.size());grid.setItems(p.getContent());pagination.setTotal(p.getTotalElements());}catch(RuntimeException e){error(e,"No fue posible cargar la configuración fiscal.");}}void reset(){pagination.reset();recargar();}
  void dialog(ComprobanteFiscalDto x){boolean nuevo=x==null;var d=ConfiguracionFiscalView.dialog(nuevo?"Nuevo comprobante fiscal":"Editar comprobante fiscal");var codigo=text("Código",nuevo?"":x.codigo());codigo.setRequired(true);codigo.setMaxLength(30);var nombre=text("Nombre",nuevo?"":x.nombre());nombre.setRequired(true);var prefijo=text("Prefijo",nuevo?"":x.prefijo());prefijo.setRequired(true);prefijo.setMaxLength(20);boolean[] prefijoManual={!nuevo};codigo.addValueChangeListener(e->{if(e.isFromClient()&&!prefijoManual[0])prefijo.setValue(e.getValue().trim().toUpperCase(Locale.ROOT));});prefijo.addValueChangeListener(e->{if(e.isFromClient())prefijoManual[0]=true;});var desc=area("Descripción",nuevo?null:x.descripcion());var activo=new Checkbox("Activo",nuevo||x.activo());activo.setReadOnly(true);d.add(form(codigo,nombre,prefijo,activo,desc));if(nuevo||has("comprobantes_fiscales.editar"))d.getFooter().add(save(e->{try{var in=new ComprobanteFiscalInput(codigo.getValue(),nombre.getValue(),prefijo.getValue(),desc.getValue());if(nuevo)comprobantes.crear(in);else comprobantes.actualizar(x.id(),in);d.close();recargar();ok(nuevo?"Comprobante creado.":"Comprobante actualizado.");}catch(RuntimeException ex){error(ex,"No fue posible guardar el comprobante.");}}));if(!nuevo&&has("comprobantes_fiscales.desactivar"))d.getFooter().add(state(x.activo(),e->{try{comprobantes.cambiarEstado(x.id(),!x.activo());d.close();recargar();ok(x.activo()?"Comprobante desactivado.":"Comprobante reactivado.");}catch(RuntimeException ex){error(ex,"No fue posible cambiar el estado.");}}));d.getFooter().add(cancel(d));d.open();}
  void detalle(ComprobanteFiscalDto x){var d=ConfiguracionFiscalView.dialog("Detalle del comprobante fiscal");d.add(new AppDetailSection("Información").field("Código",x.codigo()).field("Estado",x.activo()?"Activo":"Inactivo").field("Nombre",x.nombre()).field("Prefijo",x.prefijo()).field("Descripción",x.descripcion()));d.getFooter().add(close(d));d.open();}
 }
 private final class PanelSecuencias extends PanelFiscal{
  final TextField buscar=search("Buscar secuencia...");final ComboBox<String> estado=status();final AppGrid<SecuenciaFiscalDto> grid=new AppGrid<>(SecuenciaFiscalDto.class);final AppPagination pagination;
  PanelSecuencias(){super("SECUENCIAS","Administra las secuencias utilizadas para numerar los comprobantes fiscales de la empresa.");encabezado(has("secuencias.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nueva secuencia",e->dialog(null)):null);grid.addColumn(SecuenciaFiscalDto::comprobante).setHeader("Comprobante").setAutoWidth(true).setFlexGrow(1);grid.addColumn(SecuenciaFiscalDto::numeroActual).setHeader("Número actual").setAutoWidth(true);grid.addColumn(SecuenciaFiscalDto::siguiente).setHeader("Siguiente número").setAutoWidth(true);grid.addColumn(x->x.numeroFinal()==null?"Sin límite":x.numeroFinal().toString()).setHeader("Número final").setAutoWidth(true);grid.addComponentColumn(x->badge(x.estado())).setHeader("Estado").setAutoWidth(true);grid.addComponentColumn(this::acciones).setHeader("Acciones").setAutoWidth(true).setFlexGrow(0);grid.setEmptyStateText("No hay secuencias configuradas.");pagination=new AppPagination(r->recargar());buscar.addValueChangeListener(e->reset());estado.addValueChangeListener(e->reset());add(toolbar(buscar,estado),grid,pagination);}
  Component acciones(SecuenciaFiscalDto x){var a=actions();a.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver secuencia",e->detalle(x)));if(has("secuencias.editar")||has("secuencias.desactivar"))a.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar secuencia",e->dialog(x)));return a;}
  void cargarDatos(){try{var r=pagination.currentRequest();var p=secuencias.buscar(buscar.getValue(),active(estado),r.page(),r.size());grid.setItems(p.getContent());pagination.setTotal(p.getTotalElements());}catch(RuntimeException e){error(e,"No fue posible cargar la configuración fiscal.");}}void reset(){pagination.reset();recargar();}
  void dialog(SecuenciaFiscalDto x){boolean nuevo=x==null;var d=ConfiguracionFiscalView.dialog(nuevo?"Nueva secuencia":"Editar secuencia");var comp=new ComboBox<ComprobanteFiscalDto>("Comprobante fiscal");List<ComprobanteFiscalDto> opciones=comprobantes.activos();comp.setItems(opciones);comp.setItemLabelGenerator(c->c.codigo()+" – "+c.nombre()+" · Prefijo "+c.prefijo());if(!nuevo)opciones.stream().filter(c->c.id().equals(x.comprobanteId())).findFirst().ifPresent(comp::setValue);boolean utilizada=!nuevo&&x.numeroActual()>=x.numeroInicial();comp.setReadOnly(utilizada);var inicial=number("Número inicial",nuevo?1:x.numeroInicial());inicial.setReadOnly(utilizada);var actual=number("Número actual",nuevo?0:x.numeroActual());actual.setReadOnly(true);if(nuevo)inicial.addValueChangeListener(e->{if(e.isFromClient()){try{actual.setValue(Long.toString(Math.max(0,Long.parseLong(e.getValue())-1)));}catch(NumberFormatException ignored){actual.clear();}}});var fin=number("Número final",nuevo?null:x.numeroFinal());var activo=new Checkbox("Activo",nuevo||!"Inactiva".equals(x.estado()));activo.setReadOnly(true);d.add(form(comp,inicial,actual,fin,activo));if(nuevo||has("secuencias.editar"))d.getFooter().add(save(e->{try{long ini=parse(inicial,"El número inicial es obligatorio.");Long ultimo=parseOptional(fin);var seleccionado=comp.getValue();var in=new SecuenciaFiscalInput(seleccionado==null?null:seleccionado.id(),ini,ultimo);if(nuevo)secuencias.crear(in);else secuencias.actualizar(x.id(),in);d.close();recargar();ok(nuevo?"Secuencia creada.":"Secuencia actualizada.");}catch(RuntimeException ex){error(ex,"No fue posible guardar la secuencia.");}}));if(!nuevo&&has("secuencias.desactivar")&&!"Agotada".equals(x.estado())){boolean activa="Activa".equals(x.estado());d.getFooter().add(state(activa,e->{try{secuencias.cambiarEstado(x.id(),!activa);d.close();recargar();ok(activa?"Secuencia desactivada.":"Secuencia reactivada.");}catch(RuntimeException ex){error(ex,"No fue posible cambiar el estado.");}}));}d.getFooter().add(cancel(d));d.open();}
  void detalle(SecuenciaFiscalDto x){var d=ConfiguracionFiscalView.dialog("Detalle de la secuencia");d.add(new AppDetailSection("Información").field("Comprobante",x.comprobante()).field("Estado",x.estado()).field("Número inicial",Long.toString(x.numeroInicial())).field("Número actual",Long.toString(x.numeroActual())).field("Siguiente número",Long.toString(x.siguiente())).field("Número final",x.numeroFinal()==null?"Sin límite":x.numeroFinal().toString()));d.getFooter().add(close(d));d.open();}
 }
 private static TextField search(String placeholder){var f=new TextField();f.setPlaceholder(placeholder);f.setClearButtonVisible(true);f.setValueChangeMode(ValueChangeMode.LAZY);return f;}private static ComboBox<String> status(){var c=new ComboBox<String>("Estado");c.setItems("Todos","Activo","Inactivo");c.setValue("Todos");return c;}private static Boolean active(ComboBox<String> c){return switch(c.getValue()==null?"Todos":c.getValue()){case"Activo"->true;case"Inactivo"->false;default->null;};}
 private static HorizontalLayout toolbar(Component... c){var l=new HorizontalLayout(c);l.addClassName("cc-filter-bar");l.setAlignItems(Alignment.END);return l;}private static HorizontalLayout actions(){var l=new HorizontalLayout();l.addClassName("cc-grid-actions");l.setPadding(false);l.setSpacing(false);return l;}private static Span badge(String s){var x=new Span(s);x.getElement().getThemeList().add("badge "+("Activo".equals(s)||"Activa".equals(s)?"success":"Agotada".equals(s)?"error":"contrast"));return x;}
 private static Dialog dialog(Object title){var d=new Dialog();d.setHeaderTitle(String.valueOf(title));d.setWidth("min(760px, 96vw)");return d;}private static Div form(Component... c){var d=new Div(c);d.addClassName("cc-dialog-form");return d;}private static Div section(String title,Component...components){Div section=new Div();section.addClassName("cc-form-section");H3 heading=new H3(title);heading.addClassName("cc-section-heading");section.add(heading,form(components));return section;}private static TextField text(String l,String v){var f=new TextField(l);f.setValue(v==null?"":v);return f;}private static TextArea area(String l,String v){var f=new TextArea(l);f.setValue(v==null?"":v);f.addClassName("cc-dialog-span-2");return f;}private static TextField number(String l,Long v){var f=new TextField(l);f.setAllowedCharPattern("[0-9]");if(v!=null)f.setValue(v.toString());return f;}private static long parse(TextField f,String message){try{if(f.getValue().isBlank())throw new NumberFormatException();return Long.parseLong(f.getValue());}catch(NumberFormatException e){throw new ReglaNegocioException(message);}}private static Long parseOptional(TextField f){return f.getValue().isBlank()?null:parse(f,"El número final no es válido.");}
 private static AppActionButton save(ComponentEventListener<com.vaadin.flow.component.ClickEvent<com.vaadin.flow.component.button.Button>> e){return new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",e);}private static AppActionButton state(boolean activo,ComponentEventListener<com.vaadin.flow.component.ClickEvent<com.vaadin.flow.component.button.Button>> e){return new AppActionButton(activo?ActionType.DEACTIVATE:ActionType.ACTIVATE,ButtonSize.MAIN,activo?"Desactivar":"Reactivar",e);}private static AppActionButton cancel(Dialog d){return new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close());}private static AppActionButton close(Dialog d){return new AppActionButton(ActionType.CLOSE,ButtonSize.MAIN,"Cerrar",e->d.close());}
 private static String porcentaje(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP).toPlainString()+"%";}private static boolean has(String p){return TenantContext.principalActual().permisos().contains(p);}private static boolean hasAny(String...p){return Arrays.stream(p).anyMatch(ConfiguracionFiscalView::has);}private static void ok(String s){Notification.show(s);}private static void error(RuntimeException e,String fallback){Notification.show(e.getMessage()==null||e.getMessage().isBlank()?fallback:e.getMessage());}
}
