package com.citacloud.springboot.contacloud.app.views;

import com.citacloud.springboot.contacloud.app.dto.*;
import com.citacloud.springboot.contacloud.app.models.*;
import com.citacloud.springboot.contacloud.app.security.TenantContext;
import com.citacloud.springboot.contacloud.app.services.*;
import com.citacloud.springboot.contacloud.app.views.components.*;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.*;
import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.Consumer;

@Route(value="facturas-proveedores",layout=MainLayout.class) @PageTitle("Facturas de proveedores | ContaCloud") @PermitAll
public class FacturasProveedoresView extends VerticalLayout implements BeforeEnterObserver {
    private static final DateTimeFormatter DATE=DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private final PurchaseInvoiceService service;private final EmpresaModuloService modules;private final PurchaseOrderCalculationService calculations;
    private final TextField search=new TextField("Buscar");private final DatePicker from=new DatePicker("Desde"),to=new DatePicker("Hasta");private final Select<EstadoFacturaProveedor> status=new Select<>();
    private final AppGrid<FacturaProveedorDto> grid=new AppGrid<>(FacturaProveedorDto.class);private final AppPagination pagination;
    public FacturasProveedoresView(PurchaseInvoiceService service,EmpresaModuloService modules,PurchaseOrderCalculationService calculations){this.service=service;this.modules=modules;this.calculations=calculations;addClassName("cc-page");setPadding(false);setSpacing(false);setWidthFull();
        Component action=can("facturas_proveedores.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nueva factura",e->form(null)):null;add(action==null?new AppPageHeader("FACTURAS DE PROVEEDORES","Registra documentos recibidos y genera cuentas por pagar sin modificar inventario."):new AppPageHeader("FACTURAS DE PROVEEDORES","Registra documentos recibidos y genera cuentas por pagar sin modificar inventario.",action));
        search.setPlaceholder("Número, NCF o proveedor...");search.setClearButtonVisible(true);search.setValueChangeMode(ValueChangeMode.LAZY);search.setValueChangeTimeout(350);status.setLabel("Estado");status.setItems(EstadoFacturaProveedor.values());status.setItemLabelGenerator(FacturasProveedoresView::state);status.setEmptySelectionAllowed(true);status.setPlaceholder("Todos");
        search.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});from.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});to.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});status.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});HorizontalLayout filters=new HorizontalLayout(search,from,to,status);filters.addClassName("cc-filter-bar");filters.setAlignItems(Alignment.END);configureGrid();pagination=new AppPagination(r->load());add(filters,grid,pagination);}
    @Override public void beforeEnter(BeforeEnterEvent e){if(!modules.habilitado("COMPRAS")||!can("facturas_proveedores.ver")){Notification.show("No tienes permiso para acceder a esta opción.");e.rerouteTo(DashboardView.class);return;}load();}
    private void configureGrid(){grid.addColumn(FacturaProveedorDto::numeroFactura).setHeader("Factura").setAutoWidth(true);grid.addColumn(FacturaProveedorDto::proveedor).setHeader("Proveedor").setFlexGrow(1);grid.addColumn(x->DATE.format(x.fecha())).setHeader("Fecha").setAutoWidth(true);grid.addColumn(x->DATE.format(x.vencimiento())).setHeader("Vence").setAutoWidth(true);grid.addColumn(x->money(x.total())).setHeader("Total").setAutoWidth(true);grid.addColumn(x->x.moneda()==null?"—":x.moneda()).setHeader("Moneda").setAutoWidth(true);grid.addComponentColumn(x->badge(x.estado())).setHeader("Estado").setAutoWidth(true);grid.addComponentColumn(this::actions).setHeader("Acciones").setAutoWidth(true);grid.setEmptyStateText("No hay facturas de proveedores registradas.");}
    private Component actions(FacturaProveedorDto x){HorizontalLayout h=actions();h.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver factura",e->detail(x.id())));if(x.estado()==EstadoFacturaProveedor.DRAFT&&can("facturas_proveedores.editar"))h.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar factura",e->form(x.id())));return h;}
    private void load(){try{var r=pagination.currentRequest();var p=service.search(search.getValue(),from.getValue(),to.getValue(),status.getValue(),r.page(),r.size());grid.setItems(p.getContent());pagination.setTotal(p.getTotalElements());}catch(RuntimeException e){error(e,"No fue posible cargar las facturas.");}}
    private void reloadFirst(){pagination.reset();load();}

    private void form(UUID id){try{FacturaProveedorDto current=id==null?null:service.get(id);var catalogs=service.catalogs(current==null?null:current.proveedorId());var taxes=service.taxOptions();Dialog d=dialog(current==null?"NUEVA FACTURA DE PROVEEDOR":"EDITAR FACTURA DE PROVEEDOR");
        ComboBox<ComprasCatalogosDto.Opcion> supplier=combo("Proveedor",catalogs.proveedores()),branch=combo("Sucursal",catalogs.sucursales()),currency=combo("Moneda",catalogs.monedas()),term=combo("Condición de pago",catalogs.condicionesPago()),order=combo("Orden de compra (opcional)",catalogs.ordenes());TextField number=new TextField("Número de factura"),fiscal=new TextField("NCF / Número fiscal"),reference=new TextField("Referencia");DatePicker date=new DatePicker("Fecha"),due=new DatePicker("Vencimiento");TextArea notes=new TextArea("Notas");number.setRequiredIndicatorVisible(true);supplier.setRequiredIndicatorVisible(true);branch.setRequiredIndicatorVisible(true);currency.setRequiredIndicatorVisible(true);term.setRequiredIndicatorVisible(true);date.setRequiredIndicatorVisible(true);due.setRequiredIndicatorVisible(true);number.setMaxLength(100);fiscal.setMaxLength(50);reference.setMaxLength(100);notes.setMaxLength(1000);
        List<LineDraft> lines=new ArrayList<>();Span subtotalValue=new Span(),discountValue=new Span(),taxValue=new Span(),totalValue=new Span();
        Runnable refreshTotals=()->refreshInvoiceTotals(lines,currency,subtotalValue,discountValue,taxValue,totalValue);
        Grid<LineDraft> lineGrid=new Grid<>(LineDraft.class,false);lineGrid.setAllRowsVisible(true);lineGrid.setWidthFull();lineGrid.addColumn(x->x.product().codigo()).setHeader("Código").setAutoWidth(true);lineGrid.addColumn(x->x.product().nombre()).setHeader("Producto / Servicio").setFlexGrow(1);lineGrid.addColumn(x->x.quantity().toPlainString()).setHeader("Cantidad").setAutoWidth(true);lineGrid.addColumn(x->money(x.price())).setHeader("Precio").setAutoWidth(true);lineGrid.addColumn(x->money(x.discount())).setHeader("Descuento").setAutoWidth(true);lineGrid.addColumn(x->money(x.calculated().taxAmount())).setHeader("Impuesto").setAutoWidth(true);lineGrid.addColumn(x->money(x.calculated().total())).setHeader("Total").setAutoWidth(true);lineGrid.addComponentColumn(x->{HorizontalLayout h=actions();h.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar línea",e->lineForm(taxes,x,lines,()->{lineGrid.setItems(lines);refreshTotals.run();})),new AppActionButton(ActionType.DELETE,ButtonSize.GRID_ACTION,"Quitar línea",e->{lines.remove(x);lineGrid.setItems(lines);refreshTotals.run();}));return h;}).setHeader("Acciones").setAutoWidth(true);
        if(current==null){date.setValue(LocalDate.now());due.setValue(LocalDate.now());select(currency,catalogs.monedas(),catalogs.monedaBaseId());select(term,catalogs.condicionesPago(),catalogs.condicionPagoCreditoId());}else{select(supplier,catalogs.proveedores(),current.proveedorId());select(branch,catalogs.sucursales(),current.sucursalId());select(currency,catalogs.monedas(),current.monedaId());select(term,catalogs.condicionesPago(),current.condicionPagoId());select(order,catalogs.ordenes(),current.ordenCompraId());number.setValue(value(current.numeroFactura()));fiscal.setValue(value(current.numeroFiscal()));date.setValue(current.fecha());due.setValue(current.vencimiento());reference.setValue(value(current.referencia()));notes.setValue(value(current.notas()));for(var l:current.lineas()){var p=service.productOption(l.productoId());var tax=taxes.stream().filter(t->Objects.equals(t.id(),l.impuestoId())).findFirst().orElse(null);var c=calculations.calculate(new LineaOrdenCompraInput(p.id(),l.descripcion(),l.cantidad(),l.precioUnitario(),l.descuento(),l.impuestoId()),tax==null?null:tax.nombre(),tax==null?BigDecimal.ZERO:tax.tasa());lines.add(new LineDraft(p,l.descripcion(),l.cantidad(),l.precioUnitario(),l.descuento(),tax,c));}lineGrid.setItems(lines);}
        currency.addValueChangeListener(e->refreshTotals.run());
        Runnable refreshDue=()->{var selected=term.getValue();if(selected==null||date.getValue()==null)return;
            var detail=catalogs.detallesCondicionesPago().get(selected.id());if(detail!=null)due.setValue(detail.tipo()==TipoCondicionPago.CASH
                ?date.getValue():date.getValue().plusDays(Math.max(0,detail.dias())));};
        term.addValueChangeListener(e->refreshDue.run());date.addValueChangeListener(e->refreshDue.run());
        refreshTotals.run();
        supplier.addValueChangeListener(e->{if(e.getValue()==null)return;var c=service.catalogs(e.getValue().id());order.setItems(c.ordenes());if(e.isFromClient()){order.clear();UUID defaultTerm=c.condicionPagoProveedorIds().get(e.getValue().id());if(defaultTerm!=null)select(term,c.condicionesPago(),defaultTerm);}});order.addValueChangeListener(e->{if(!e.isFromClient()||e.getValue()==null)return;try{lines.clear();for(var l:service.linesFromOrder(e.getValue().id())){var p=service.productOption(l.productoId());var tax=taxes.stream().filter(t->Objects.equals(t.id(),l.impuestoId())).findFirst().orElse(null);var c=calculations.calculate(new LineaOrdenCompraInput(p.id(),l.descripcion(),l.cantidad(),l.precioUnitario(),l.descuento(),l.impuestoId()),tax==null?null:tax.nombre(),tax==null?BigDecimal.ZERO:tax.tasa());lines.add(new LineDraft(p,l.descripcion(),l.cantidad(),l.precioUnitario(),l.descuento(),tax,c));}lineGrid.setItems(lines);refreshTotals.run();}catch(RuntimeException ex){error(ex,"No fue posible cargar la orden.");}});
        AppActionButton addLine=new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Agregar línea",e->lineForm(taxes,null,lines,()->{lineGrid.setItems(lines);refreshTotals.run();}));HorizontalLayout lineHeader=new HorizontalLayout(new H3("DETALLE"),addLine);lineHeader.setWidthFull();lineHeader.setJustifyContentMode(JustifyContentMode.BETWEEN);lineHeader.setAlignItems(Alignment.CENTER);d.add(section("INFORMACIÓN GENERAL",supplier,branch,number,fiscal,date,due,term,currency,order,reference,notes),lineHeader,lineGrid,invoiceTotals(subtotalValue,discountValue,taxValue,totalValue));
        AppActionButton save=new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",null);save.addClickListener(e->{save.setEnabled(false);try{FacturaProveedorInput input=input(supplier,branch,number,fiscal,date,due,term,currency,order,reference,notes,lines,current);if(current==null)service.create(input);else service.update(current.id(),input);d.close();load();Notification.show("Factura guardada correctamente.");}catch(RuntimeException ex){save.setEnabled(true);error(ex,"No fue posible guardar la factura.");}});
        if(can("facturas_proveedores.registrar")){AppActionButton register=new AppActionButton(ActionType.ISSUE,ButtonSize.MAIN,"Registrar factura",null);register.addClickListener(e->{register.setEnabled(false);save.setEnabled(false);try{FacturaProveedorInput input=input(supplier,branch,number,fiscal,date,due,term,currency,order,reference,notes,lines,current);FacturaProveedorRegistroPreviewDto preview=service.previewRegistration(current==null?null:current.id(),input);showRegistration(supplier.getValue()==null?null:supplier.getValue().nombre(),number.getValue(),date.getValue(),currency.getValue()==null?null:currency.getValue().nombre(),currency.getValue()==null?null:currency.getValue().id(),preview,payment->{try{if(current==null)service.createAndRegister(input,payment);else service.updateAndRegister(current.id(),input,payment);d.close();load();Notification.show(preview.tipoCondicionPago()==TipoCondicionPago.CASH?"Factura registrada y pagada correctamente.":"Factura registrada y cuenta por pagar creada.");}catch(RuntimeException ex){register.setEnabled(true);save.setEnabled(true);error(ex,"No fue posible guardar y registrar la factura.");}},()->{register.setEnabled(true);save.setEnabled(true);});}catch(RuntimeException ex){register.setEnabled(true);save.setEnabled(true);error(ex,"No fue posible validar la factura.");}});d.getFooter().add(register);}
        d.getFooter().add(save,new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}catch(RuntimeException e){error(e,"No fue posible abrir la factura.");}}
    private void refreshInvoiceTotals(List<LineDraft> lines,ComboBox<ComprasCatalogosDto.Opcion> currency,
            Span subtotal,Span discount,Span tax,Span total){
        BigDecimal subtotalAmount=BigDecimal.ZERO,discountAmount=BigDecimal.ZERO,taxAmount=BigDecimal.ZERO,totalAmount=BigDecimal.ZERO;
        if(!lines.isEmpty()){
            var totals=calculations.totals(lines.stream().map(LineDraft::calculated).toList());
            subtotalAmount=totals.subtotal();discountAmount=totals.discount();taxAmount=totals.tax();totalAmount=totals.total();
        }
        String code=currency.getValue()==null?"":currency.getValue().nombre().split("\\s*[·-]\\s*",2)[0].trim()+" ";
        subtotal.setText(code+money(subtotalAmount));discount.setText(code+money(discountAmount));
        tax.setText(code+money(taxAmount));total.setText(code+money(totalAmount));
    }
    private static Div invoiceTotals(Span subtotal,Span discount,Span tax,Span total){
        Div box=new Div();box.addClassName("cc-invoice-totals");
        box.getStyle().set("margin-left","auto").set("width","min(420px, 100%)").set("padding","var(--lumo-space-m)")
            .set("border","1px solid var(--lumo-contrast-20pct)").set("border-radius","var(--lumo-border-radius-m)");
        box.add(totalRow("Subtotal",subtotal,false),totalRow("Descuento",discount,false),
            totalRow("Impuesto",tax,false),totalRow("TOTAL",total,true));return box;
    }
    private static HorizontalLayout totalRow(String label,Span value,boolean main){
        Span name=new Span(label);HorizontalLayout row=new HorizontalLayout(name,value);row.setWidthFull();
        row.setJustifyContentMode(JustifyContentMode.BETWEEN);if(main)row.getStyle().set("font-weight","700").set("font-size","var(--lumo-font-size-l)")
            .set("border-top","1px solid var(--lumo-contrast-20pct)").set("padding-top","var(--lumo-space-s)");return row;
    }
    private void showRegisterConfirmation(String supplier,String invoiceNumber,LocalDate date,
            String currency,FacturaProveedorTotalesDto totals,Runnable confirm,Runnable cancel){
        String currencyLabel=value(currency);
        ConfirmDialog dialog=new ConfirmDialog();dialog.setHeader("REGISTRAR FACTURA DE PROVEEDOR");
        dialog.setText("Proveedor: "+(supplier==null?"—":supplier)+"\nFactura: "+value(invoiceNumber)
            +"\nFecha: "+(date==null?"—":DATE.format(date))+"\nMoneda: "+currencyLabel
            +"\n\nSubtotal: "+money(totals.subtotal())+"\nDescuento: "+money(totals.descuento())
            +"\nImpuesto: "+money(totals.impuesto())+"\nTOTAL FACTURA: "+money(totals.total())
            +"\n\nCUENTA POR PAGAR A CREAR: "+money(totals.total())
            +"\n\nRegistrar la factura no generará movimientos de inventario.");
        dialog.setConfirmText("Registrar");dialog.setCancelText("Cancelar");dialog.setCancelable(true);
        dialog.addConfirmListener(e->confirm.run());dialog.addCancelListener(e->cancel.run());dialog.open();
    }
    private void showRegistration(String supplier,String invoiceNumber,LocalDate date,String currency,UUID currencyId,
            FacturaProveedorRegistroPreviewDto preview,Consumer<PagoFacturaProveedorInput> confirm,Runnable cancel){
        if(preview.tipoCondicionPago()==TipoCondicionPago.CREDIT){showRegisterConfirmation(supplier,invoiceNumber,date,currency,
            new FacturaProveedorTotalesDto(preview.subtotal(),preview.descuento(),preview.impuesto(),preview.total()),
            ()->confirm.accept(null),cancel);return;}
        if(!can("facturas_proveedores.pagar_contado")){cancel.run();throw new ReglaNegocioException("No tienes permiso para registrar pagos de facturas al contado.");}
        Dialog dialog=dialog("REGISTRAR Y PAGAR FACTURA AL CONTADO");Select<TipoCuentaDinero> sourceType=new Select<>();
        sourceType.setLabel("Tipo de fuente");sourceType.setItems(TipoCuentaDinero.CASH_REGISTER,TipoCuentaDinero.BANK_ACCOUNT);
        sourceType.setItemLabelGenerator(t->t==TipoCuentaDinero.CASH_REGISTER?"Caja":"Cuenta bancaria");
        ComboBox<CuentaDineroOpcionDto> source=new ComboBox<>("Fuente de pago");source.setItemLabelGenerator(CuentaDineroOpcionDto::nombre);
        TextField reference=new TextField("Referencia");reference.setMaxLength(100);
        sourceType.addValueChangeListener(e->{source.clear();if(e.getValue()!=null)source.setItems(q->service.searchPaymentSources(
            e.getValue(),currencyId,q.getFilter().orElse(""),q.getOffset(),q.getLimit()).stream());});
        sourceType.setValue(TipoCuentaDinero.BANK_ACCOUNT);
        Span amount=new Span((currency==null?"":currency+" ")+money(preview.total()));amount.getStyle().set("font-weight","700");
        dialog.add(section("PAGO",sourceType,source,reference),new H4("Total a pagar"),amount,
            new Paragraph("La factura y el egreso se registrarán juntos. Si una operación falla, no se guardará ninguna."));
        dialog.getFooter().add(new AppActionButton(ActionType.ISSUE,ButtonSize.MAIN,"Registrar y pagar",e->{
            try{if(source.getValue()==null)throw new ReglaNegocioException("Selecciona la fuente de pago.");
                confirm.accept(new PagoFacturaProveedorInput(sourceType.getValue(),source.getValue().id(),
                    sourceType.getValue()==TipoCuentaDinero.CASH_REGISTER?MedioPagoMovimiento.CASH:MedioPagoMovimiento.BANK_TRANSFER,
                    reference.getValue(),UUID.randomUUID()));dialog.close();}
            catch(RuntimeException ex){error(ex,"No fue posible registrar el pago de la factura.");}}),
            new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->{dialog.close();cancel.run();}));dialog.open();
    }
    private void lineForm(List<OrdenCompraCatalogosDto.ImpuestoOpcion> taxes,LineDraft current,List<LineDraft> lines,Runnable refresh){Dialog d=dialog(current==null?"AGREGAR LÍNEA":"EDITAR LÍNEA");ComboBox<OrdenCompraCatalogosDto.ProductoOpcion> product=new ComboBox<>("Producto / Servicio");product.setItems(q->service.searchProducts(q.getFilter().orElse(""),q.getOffset(),q.getLimit()).stream());product.setItemLabelGenerator(x->x.codigo()+" · "+x.nombre());TextArea description=new TextArea("Descripción");BigDecimalField quantity=new BigDecimalField("Cantidad"),price=new BigDecimalField("Precio unitario"),discount=new BigDecimalField("Descuento");ComboBox<OrdenCompraCatalogosDto.ImpuestoOpcion> tax=new ComboBox<>("Impuesto");tax.setItems(taxes);tax.setItemLabelGenerator(x->x.nombre()+" ("+x.tasa()+"%)");tax.setClearButtonVisible(true);if(current==null){quantity.setValue(BigDecimal.ONE);price.setValue(BigDecimal.ZERO);discount.setValue(BigDecimal.ZERO);}else{product.setValue(current.product());description.setValue(current.description());quantity.setValue(current.quantity());price.setValue(current.price());discount.setValue(current.discount());tax.setValue(current.tax());}product.addValueChangeListener(e->{if(e.isFromClient()&&e.getValue()!=null){description.setValue(e.getValue().nombre());price.setValue(e.getValue().costoCompra()==null?BigDecimal.ZERO:e.getValue().costoCompra());selectTax(tax,taxes,e.getValue().impuestoCompraId());}});d.add(section("LÍNEA",product,description,quantity,price,discount,tax));d.getFooter().add(new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar línea",e->{try{if(product.getValue()==null)throw new ReglaNegocioException("Selecciona un producto o servicio.");if(lines.stream().anyMatch(x->x!=current&&Objects.equals(x.product().id(),product.getValue().id())))throw new ReglaNegocioException("El producto ya existe en la factura.");var t=tax.getValue();var c=calculations.calculate(new LineaOrdenCompraInput(product.getValue().id(),description.getValue(),quantity.getValue(),price.getValue(),discount.getValue(),t==null?null:t.id()),t==null?null:t.nombre(),t==null?BigDecimal.ZERO:t.tasa());LineDraft n=new LineDraft(product.getValue(),c.description(),c.quantity(),c.unitPrice(),c.discount(),t,c);if(current==null)lines.add(n);else lines.set(lines.indexOf(current),n);refresh.run();d.close();}catch(RuntimeException ex){error(ex,"No fue posible guardar la línea.");}}),new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}
    private static FacturaProveedorInput input(ComboBox<ComprasCatalogosDto.Opcion> supplier,ComboBox<ComprasCatalogosDto.Opcion> branch,TextField number,TextField fiscal,DatePicker date,DatePicker due,ComboBox<ComprasCatalogosDto.Opcion> term,ComboBox<ComprasCatalogosDto.Opcion> currency,ComboBox<ComprasCatalogosDto.Opcion> order,TextField reference,TextArea notes,List<LineDraft> lines,FacturaProveedorDto current){return new FacturaProveedorInput(id(supplier),id(branch),number.getValue(),fiscal.getValue(),date.getValue(),due.getValue(),id(term),id(currency),id(order),reference.getValue(),notes.getValue(),lines.stream().map(x->new LineaFacturaProveedorInput(x.product().id(),x.description(),x.quantity(),x.price(),x.discount(),x.tax()==null?null:x.tax().id())).toList(),current==null?null:current.version());}
    private void detail(UUID id){try{var x=service.get(id);Dialog d=dialog("FACTURA DE PROVEEDOR");Grid<LineaFacturaProveedorDto> lines=new Grid<>(LineaFacturaProveedorDto.class,false);lines.setAllRowsVisible(true);lines.addColumn(LineaFacturaProveedorDto::codigo).setHeader("Código");lines.addColumn(LineaFacturaProveedorDto::descripcion).setHeader("Descripción").setFlexGrow(1);lines.addColumn(l->l.cantidad().toPlainString()).setHeader("Cantidad");lines.addColumn(l->money(l.descuento())).setHeader("Descuento");lines.addColumn(l->money(l.impuesto())).setHeader("Impuesto");lines.addColumn(l->money(l.total())).setHeader("Total");lines.setItems(x.lineas());d.add(new AppDetailSection("INFORMACIÓN").field("Proveedor",x.proveedor()).field("Factura",x.numeroFactura()).field("NCF / Número fiscal",x.numeroFiscal()).field("Fecha",DATE.format(x.fecha())).field("Vencimiento",DATE.format(x.vencimiento())).field("Condición de pago",x.condicionPago()).field("Estado",state(x.estado())).field("Estado financiero",x.estadoFinanciero()==null?"—":x.estadoFinanciero().name()).field("Moneda",x.moneda()).field("Subtotal",money(x.subtotal())).field("Descuento",money(x.descuento())).field("Impuesto",money(x.impuesto())).field("Total",money(x.total())).field("Saldo por pagar",x.saldo()==null?"—":money(x.saldo())),lines);if(x.estado()==EstadoFacturaProveedor.DRAFT&&can("facturas_proveedores.registrar"))d.getFooter().add(new AppActionButton(ActionType.ISSUE,ButtonSize.MAIN,"Registrar factura",e->{FacturaProveedorRegistroPreviewDto preview=new FacturaProveedorRegistroPreviewDto(x.subtotal(),x.descuento(),x.impuesto(),x.total(),x.condicionPagoId(),x.condicionPago(),x.tipoCondicionPago(),x.diasCondicionPago()==null?0:x.diasCondicionPago(),x.vencimiento());showRegistration(x.proveedor(),x.numeroFactura(),x.fecha(),x.moneda(),x.monedaId(),preview,payment->{try{service.register(x.id(),x.version(),payment);d.close();load();Notification.show(preview.tipoCondicionPago()==TipoCondicionPago.CASH?"Factura registrada y pagada correctamente.":"Factura registrada y cuenta por pagar creada.");}catch(RuntimeException ex){error(ex,"No fue posible registrar la factura.");}},()->{});}));if(x.estado()!=EstadoFacturaProveedor.VOIDED&&can("facturas_proveedores.anular"))d.getFooter().add(new AppActionButton(ActionType.VOID,ButtonSize.MAIN,"Anular factura",e->voidDialog(x,d)));d.getFooter().add(new AppActionButton(ActionType.CLOSE,ButtonSize.MAIN,"Cerrar",e->d.close()));d.open();}catch(RuntimeException e){error(e,"No fue posible consultar la factura.");}}
    private void voidDialog(FacturaProveedorDto x,Dialog parent){Dialog d=dialog("ANULAR FACTURA");TextArea reason=new TextArea("Motivo de anulación");reason.setRequiredIndicatorVisible(true);d.add(reason);d.getFooter().add(new AppActionButton(ActionType.VOID,ButtonSize.MAIN,"Anular",e->{try{service.voidInvoice(x.id(),x.version(),reason.getValue());d.close();parent.close();load();Notification.show("Factura anulada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible anular la factura.");}}),new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}
    private static <T extends ComprasCatalogosDto.Opcion> ComboBox<T> combo(String label,List<T> items){ComboBox<T> c=new ComboBox<>(label);c.setItems(items);c.setItemLabelGenerator(ComprasCatalogosDto.Opcion::nombre);c.setClearButtonVisible(true);return c;}private static void select(ComboBox<ComprasCatalogosDto.Opcion> c,List<ComprasCatalogosDto.Opcion> xs,UUID id){c.setValue(xs.stream().filter(x->Objects.equals(x.id(),id)).findFirst().orElse(null));}private static void selectTax(ComboBox<OrdenCompraCatalogosDto.ImpuestoOpcion> c,List<OrdenCompraCatalogosDto.ImpuestoOpcion> xs,UUID id){c.setValue(xs.stream().filter(x->Objects.equals(x.id(),id)).findFirst().orElse(null));}private static UUID id(ComboBox<ComprasCatalogosDto.Opcion> c){return c.getValue()==null?null:c.getValue().id();}
    private static Div section(String title,Component...fields){Div d=new Div();d.addClassName("cc-form-section");d.add(new H3(title));Div f=new Div(fields);f.addClassName("cc-dialog-form");d.add(f);return d;}private static Dialog dialog(String title){Dialog d=new Dialog();d.setHeaderTitle(title);d.setWidth("min(1100px,96vw)");return d;}private static HorizontalLayout actions(){HorizontalLayout h=new HorizontalLayout();h.addClassName("cc-grid-actions");h.setSpacing(false);return h;}private static Span badge(EstadoFacturaProveedor s){Span x=new Span(state(s));x.getElement().getThemeList().add("badge "+(s==EstadoFacturaProveedor.REGISTERED?"success":s==EstadoFacturaProveedor.VOIDED?"error":"contrast"));return x;}private static String state(EstadoFacturaProveedor s){if(s==null)return "Todos";return switch(s){case DRAFT->"Borrador";case REGISTERED->"Registrada";case VOIDED->"Anulada";};}private static String money(BigDecimal v){return v==null?"—":String.format(Locale.US,"%,.2f",v);}private static String value(String v){return v==null?"":v;}private static boolean can(String p){return TenantContext.principalActual().permisos().contains(p);}private static void error(RuntimeException e,String fallback){Notification.show(e instanceof ReglaNegocioException||e instanceof RecursoNoEncontradoException?e.getMessage():fallback);}
    private record LineDraft(OrdenCompraCatalogosDto.ProductoOpcion product,String description,BigDecimal quantity,BigDecimal price,BigDecimal discount,OrdenCompraCatalogosDto.ImpuestoOpcion tax,PurchaseOrderCalculationService.CalculatedLine calculated){}
}
