package com.citacloud.springboot.contacloud.app.views;

import com.citacloud.springboot.contacloud.app.dto.*;import com.citacloud.springboot.contacloud.app.models.*;
import com.citacloud.springboot.contacloud.app.security.TenantContext;import com.citacloud.springboot.contacloud.app.services.*;
import com.citacloud.springboot.contacloud.app.views.components.*;import com.vaadin.flow.component.*;
import com.vaadin.flow.component.combobox.ComboBox;import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.datepicker.DatePicker;import com.vaadin.flow.component.dialog.Dialog;import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;import com.vaadin.flow.component.notification.Notification;import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.select.Select;import com.vaadin.flow.component.textfield.*;import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;import jakarta.annotation.security.PermitAll;import java.math.*;import java.time.LocalDate;import java.time.format.DateTimeFormatter;import java.util.*;

@Route(value="notas-credito-proveedores",layout=MainLayout.class) @PageTitle("Notas de crédito de proveedores | ContaCloud") @PermitAll
public class NotasCreditoProveedoresView extends VerticalLayout implements BeforeEnterObserver{
 private static final DateTimeFormatter DATE=DateTimeFormatter.ofPattern("dd/MM/yyyy");private final SupplierCreditNoteService service;private final EmpresaModuloService modules;private final PurchaseOrderCalculationService calculations;
 private final TextField search=new TextField("Buscar");private final ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> supplierFilter=new ComboBox<>("Proveedor");private final Select<EstadoNotaCreditoProveedor> status=new Select<>();private final DatePicker from=new DatePicker("Desde"),to=new DatePicker("Hasta");private final AppGrid<NotaCreditoProveedorDto> grid=new AppGrid<>(NotaCreditoProveedorDto.class);private final AppPagination pagination;
 public NotasCreditoProveedoresView(SupplierCreditNoteService service,EmpresaModuloService modules,PurchaseOrderCalculationService calculations){this.service=service;this.modules=modules;this.calculations=calculations;addClassName("cc-page");setPadding(false);setSpacing(false);setWidthFull();Component action=can("notas_credito_proveedores.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nueva nota de crédito",e->form(null)):null;add(action==null?new AppPageHeader("NOTAS DE CRÉDITO","Administra los créditos recibidos de proveedores."):new AppPageHeader("NOTAS DE CRÉDITO","Administra los créditos recibidos de proveedores.",action));search.setPlaceholder("Número, documento, NCF, proveedor o factura...");search.setClearButtonVisible(true);search.setValueChangeMode(ValueChangeMode.LAZY);status.setLabel("Estado");status.setItems(EstadoNotaCreditoProveedor.values());status.setItemLabelGenerator(NotasCreditoProveedoresView::state);status.setEmptySelectionAllowed(true);supplierFilter.setClearButtonVisible(true);supplierFilter.setItemLabelGenerator(NotaCreditoProveedorCatalogosDto.Opcion::nombre);search.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});supplierFilter.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});status.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});from.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});to.addValueChangeListener(e->{if(e.isFromClient())reloadFirst();});HorizontalLayout filters=new HorizontalLayout(search,supplierFilter,status,from,to);filters.addClassName("cc-filter-bar");filters.setAlignItems(Alignment.END);configureGrid();pagination=new AppPagination(r->load());add(filters,grid,pagination);}
 @Override public void beforeEnter(BeforeEnterEvent e){if(!modules.habilitado("COMPRAS")||!can("notas_credito_proveedores.ver")){Notification.show("No tienes permiso para acceder a esta opción.");e.rerouteTo(DashboardView.class);return;}try{var c=service.catalogs();supplierFilter.setItems(c.proveedores());load();}catch(RuntimeException ex){error(ex,"No fue posible abrir las notas de crédito.");}}
 private void configureGrid(){grid.addColumn(NotaCreditoProveedorDto::numero).setHeader("Número").setAutoWidth(true);grid.addColumn(x->DATE.format(x.fecha())).setHeader("Fecha").setAutoWidth(true);grid.addColumn(NotaCreditoProveedorDto::proveedor).setHeader("Proveedor").setFlexGrow(1);grid.addColumn(NotaCreditoProveedorDto::numeroProveedor).setHeader("No. nota proveedor").setAutoWidth(true);grid.addColumn(x->value(x.facturaRelacionada(),"—")).setHeader("Factura").setAutoWidth(true);grid.addColumn(NotaCreditoProveedorDto::moneda).setHeader("Moneda").setAutoWidth(true);grid.addColumn(x->money(x.total())).setHeader("Total").setAutoWidth(true);grid.addColumn(x->money(x.aplicado())).setHeader("Aplicado").setAutoWidth(true);grid.addColumn(x->money(x.disponible())).setHeader("Disponible").setAutoWidth(true);grid.addComponentColumn(x->badge(x.estado())).setHeader("Estado").setAutoWidth(true);grid.addComponentColumn(this::actions).setHeader("Acciones").setAutoWidth(true);grid.setEmptyStateText("No hay notas de crédito registradas.");}
 private Component actions(NotaCreditoProveedorDto x){HorizontalLayout h=actions();h.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver nota",e->detail(x.id())));if(x.estado()==EstadoNotaCreditoProveedor.DRAFT&&can("notas_credito_proveedores.editar"))h.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar nota",e->form(x.id())));if(x.estado()==EstadoNotaCreditoProveedor.DRAFT&&can("notas_credito_proveedores.confirmar"))h.add(new AppActionButton(ActionType.ISSUE,ButtonSize.GRID_ACTION,"Confirmar nota",e->confirm(x)));if(x.disponible().signum()>0&&x.estado()!=EstadoNotaCreditoProveedor.DRAFT&&x.estado()!=EstadoNotaCreditoProveedor.VOIDED&&can("notas_credito_proveedores.aplicar"))h.add(new AppActionButton(ActionType.APPLY_CREDIT,ButtonSize.GRID_ACTION,"Aplicar crédito",e->applyDialog(x)));return h;}
 private void load(){try{var r=pagination.currentRequest();var p=service.search(search.getValue(),supplierFilter.getValue()==null?null:supplierFilter.getValue().id(),status.getValue(),from.getValue(),to.getValue(),r.page(),r.size());grid.setItems(p.getContent());pagination.setTotal(p.getTotalElements());}catch(RuntimeException e){error(e,"No fue posible cargar las notas de crédito.");}}private void reloadFirst(){if(pagination==null)return;pagination.reset();load();}

 private void form(UUID id){try{NotaCreditoProveedorDto current=id==null?null:service.get(id);var catalogs=service.catalogs();var taxes=service.taxOptions();Dialog d=dialog(current==null?"NUEVA NOTA DE CRÉDITO":"EDITAR NOTA DE CRÉDITO");ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> supplier=combo("Proveedor",catalogs.proveedores()),currency=combo("Moneda",catalogs.monedas());ComboBox<FacturaAplicacionCreditoDto> invoice=new ComboBox<>("Factura relacionada (opcional)");invoice.setItemLabelGenerator(x->x.numero()+" · "+DATE.format(x.fecha())+" · "+x.moneda()+" "+money(x.total()));invoice.setClearButtonVisible(true);DatePicker date=new DatePicker("Fecha");TextField supplierNumber=new TextField("No. nota del proveedor"),fiscal=new TextField("NCF / e-NCF");Select<MotivoNotaCreditoProveedor> reason=new Select<>();reason.setLabel("Motivo");reason.setItems(MotivoNotaCreditoProveedor.values());reason.setItemLabelGenerator(NotasCreditoProveedoresView::reason);TextField otherReason=new TextField("Especifique el motivo");BigDecimalField rate=new BigDecimalField("Tasa de cambio");TextArea notes=new TextArea("Observación");for(Component c:List.of(supplier,date,supplierNumber,currency,reason))c.getElement().setProperty("required",true);supplierNumber.setMaxLength(100);fiscal.setMaxLength(50);notes.setMaxLength(1000);List<LineDraft> lines=new ArrayList<>();Span subtotal=new Span(),discount=new Span(),tax=new Span(),total=new Span();Runnable[] refreshRef={()->{}};Grid<LineDraft> lineGrid=lineGrid(lines,taxes,()->refreshRef[0].run());Runnable refresh=()->{lineGrid.setItems(lines);totals(lines,subtotal,discount,tax,total);};refreshRef[0]=refresh;
        if(current==null){date.setValue(LocalDate.now());select(currency,catalogs.monedas(),catalogs.monedaBaseId());reason.setValue(MotivoNotaCreditoProveedor.INVOICE_CORRECTION);}else{select(supplier,catalogs.proveedores(),current.proveedorId());select(currency,catalogs.monedas(),current.monedaId());date.setValue(current.fecha());supplierNumber.setValue(value(current.numeroProveedor(),""));fiscal.setValue(value(current.numeroFiscal(),""));reason.setValue(current.motivo());otherReason.setValue(value(current.otroMotivo(),""));rate.setValue(current.tasaCambio());notes.setValue(value(current.observacion(),""));if(current.facturaRelacionadaId()!=null)invoice.setValue(new FacturaAplicacionCreditoDto(current.facturaRelacionadaId(),current.facturaRelacionada(),current.fechaFactura(),current.monedaId(),current.moneda(),current.totalFactura(),BigDecimal.ZERO,BigDecimal.ZERO,current.saldoFactura()));for(var l:current.lineas()){var tx=taxes.stream().filter(t->Objects.equals(t.id(),l.impuestoId())).findFirst().orElse(null);var calc=calculations.calculate(new LineaOrdenCompraInput(l.productoId(),l.descripcion(),l.cantidad(),l.precio(),l.descuento(),l.impuestoId()),tx==null?null:tx.nombre(),tx==null?BigDecimal.ZERO:tx.tasa());lines.add(new LineDraft(l.lineaFacturaId(),l.productoId(),l.codigo(),l.descripcion(),l.unidad(),l.cantidadFacturada(),l.cantidad(),l.precio(),l.descuento(),tx,calc));}}
        Runnable configureInvoices=()->{if(supplier.getValue()==null){invoice.clear();invoice.setItems(List.of());return;}invoice.setItems(q->service.searchInvoices(supplier.getValue().id(),currency.getValue()==null?null:currency.getValue().id(),q.getFilter().orElse(""),q.getOffset(),q.getLimit()).stream());};supplier.addValueChangeListener(e->{if(e.isFromClient()){invoice.clear();lines.clear();refresh.run();}configureInvoices.run();});currency.addValueChangeListener(e->{if(e.isFromClient()){invoice.clear();}configureInvoices.run();});configureInvoices.run();invoice.addValueChangeListener(e->{if(!e.isFromClient()||e.getValue()==null)return;select(currency,catalogs.monedas(),e.getValue().monedaId());lines.clear();for(var l:service.invoiceLines(e.getValue().facturaId())){if(l.cantidadDisponible().signum()<=0)continue;BigDecimal proportional=l.cantidadFacturada().signum()==0?BigDecimal.ZERO:l.descuento().multiply(l.cantidadDisponible()).divide(l.cantidadFacturada(),4,RoundingMode.HALF_UP);var tx=taxes.stream().filter(t->Objects.equals(t.id(),l.impuestoId())).findFirst().orElse(null);var calc=calculations.calculate(new LineaOrdenCompraInput(l.productoId(),l.descripcion(),l.cantidadDisponible(),l.precio(),proportional,l.impuestoId()),tx==null?null:tx.nombre(),tx==null?BigDecimal.ZERO:tx.tasa());lines.add(new LineDraft(l.lineaFacturaId(),l.productoId(),l.codigo(),l.descripcion(),l.unidad(),l.cantidadFacturada(),l.cantidadDisponible(),l.precio(),proportional,tx,calc));}refresh.run();});reason.addValueChangeListener(e->otherReason.setVisible(e.getValue()==MotivoNotaCreditoProveedor.OTHER));otherReason.setVisible(reason.getValue()==MotivoNotaCreditoProveedor.OTHER);
        AppActionButton add=new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Agregar línea",e->lineForm(null,taxes,lines,refresh));HorizontalLayout header=new HorizontalLayout(new H3("DETALLE"),add);header.setWidthFull();header.setJustifyContentMode(JustifyContentMode.BETWEEN);header.setAlignItems(Alignment.CENTER);d.add(section("DATOS GENERALES",supplier,date,supplierNumber,fiscal,currency,reason,otherReason,notes),header,lineGrid,totalBox(subtotal,discount,tax,total));refresh.run();
        AppActionButton save=new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",e->{try{NotaCreditoProveedorInput input=input(supplier,date,supplierNumber,fiscal,currency,rate,reason,otherReason,invoice,notes,lines,current);if(current==null)service.create(input);else service.update(current.id(),input);d.close();load();Notification.show("Nota de crédito guardada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible guardar la nota de crédito.");}});d.getFooter().add(save);if(can("notas_credito_proveedores.confirmar")){d.getFooter().add(new AppActionButton(ActionType.ISSUE,ButtonSize.MAIN,"Confirmar",e->{try{NotaCreditoProveedorInput input=input(supplier,date,supplierNumber,fiscal,currency,rate,reason,otherReason,invoice,notes,lines,current);BigDecimal amount=lines.isEmpty()?BigDecimal.ZERO:calculations.totals(lines.stream().map(LineDraft::calculated).toList()).total();ConfirmDialog c=new ConfirmDialog("CONFIRMAR NOTA DE CRÉDITO","¿Desea confirmar la nota de crédito por "+money(amount)+"?","Confirmar",ev->{try{if(current==null)service.createAndConfirm(input);else service.updateAndConfirm(current.id(),input);d.close();load();Notification.show("Nota de crédito confirmada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible confirmar la nota de crédito.");}},"Cancelar",ev->{});c.open();}catch(RuntimeException ex){error(ex,"No fue posible validar la nota de crédito.");}}));}d.getFooter().add(new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}catch(RuntimeException e){error(e,"No fue posible abrir la nota de crédito.");}}

 private Grid<LineDraft> lineGrid(List<LineDraft> lines,List<OrdenCompraCatalogosDto.ImpuestoOpcion> taxes,Runnable changed){Grid<LineDraft> g=new Grid<>(LineDraft.class,false);g.setAllRowsVisible(true);g.setWidthFull();g.addColumn(x->value(x.code(),"—")).setHeader("Código").setAutoWidth(true);g.addColumn(LineDraft::description).setHeader("Descripción").setFlexGrow(1);g.addColumn(x->x.invoiced()==null?"—":x.invoiced().toPlainString()).setHeader("Cant. facturada").setAutoWidth(true);g.addColumn(x->x.quantity().toPlainString()).setHeader("Cant. NC").setAutoWidth(true);g.addColumn(x->money(x.price())).setHeader("Precio").setAutoWidth(true);g.addColumn(x->money(x.calculated().taxAmount())).setHeader("Impuestos").setAutoWidth(true);g.addColumn(x->money(x.calculated().total())).setHeader("Total").setAutoWidth(true);g.addComponentColumn(x->{HorizontalLayout h=actions();h.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar línea",e->lineForm(x,taxes,lines,changed)),new AppActionButton(ActionType.DELETE,ButtonSize.GRID_ACTION,"Quitar línea",e->{lines.remove(x);changed.run();}));return h;}).setHeader("Acciones").setAutoWidth(true);return g;}
 private void lineForm(LineDraft current,List<OrdenCompraCatalogosDto.ImpuestoOpcion> taxes,List<LineDraft> lines,Runnable refresh){Dialog d=dialog(current==null?"AGREGAR LÍNEA":"EDITAR LÍNEA");TextField description=new TextField("Descripción");BigDecimalField quantity=new BigDecimalField("Cantidad"),price=new BigDecimalField("Precio unitario"),discount=new BigDecimalField("Descuento");ComboBox<OrdenCompraCatalogosDto.ImpuestoOpcion> tax=new ComboBox<>("Impuesto");tax.setItems(taxes);tax.setItemLabelGenerator(x->x.nombre()+" ("+x.tasa()+"%)");tax.setClearButtonVisible(true);if(current==null){quantity.setValue(BigDecimal.ONE);price.setValue(BigDecimal.ZERO);discount.setValue(BigDecimal.ZERO);}else{description.setValue(current.description());quantity.setValue(current.quantity());price.setValue(current.price());discount.setValue(current.discount());tax.setValue(current.tax());}d.add(section("LÍNEA",description,quantity,price,discount,tax));d.getFooter().add(new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar línea",e->{try{if(current!=null&&current.invoiced()!=null&&quantity.getValue()!=null&&quantity.getValue().compareTo(current.invoiced())>0)throw new ReglaNegocioException("La cantidad de la nota no puede superar la cantidad facturada.");var tx=tax.getValue();var calc=calculations.calculate(new LineaOrdenCompraInput(current==null?null:current.productId(),description.getValue(),quantity.getValue(),price.getValue(),discount.getValue(),tx==null?null:tx.id()),tx==null?null:tx.nombre(),tx==null?BigDecimal.ZERO:tx.tasa());LineDraft next=new LineDraft(current==null?null:current.invoiceLineId(),current==null?null:current.productId(),current==null?null:current.code(),calc.description(),current==null?null:current.unit(),current==null?null:current.invoiced(),calc.quantity(),calc.unitPrice(),calc.discount(),tx,calc);if(current==null)lines.add(next);else lines.set(lines.indexOf(current),next);refresh.run();d.close();}catch(RuntimeException ex){error(ex,"No fue posible guardar la línea.");}}),new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}

 private void confirm(NotaCreditoProveedorDto x){ConfirmDialog d=new ConfirmDialog("CONFIRMAR NOTA DE CRÉDITO","¿Desea confirmar la nota de crédito "+x.numero()+" por "+x.moneda()+" "+money(x.total())+"?","Confirmar",e->{try{service.confirm(x.id(),x.version());load();Notification.show("Nota de crédito confirmada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible confirmar la nota.");}},"Cancelar",e->{});d.open();}
 private void detail(UUID id){try{
  var x=service.get(id);Dialog d=dialog("NOTA DE CRÉDITO "+x.numero());
  Grid<LineaNotaCreditoProveedorDto> lines=new Grid<>(LineaNotaCreditoProveedorDto.class,false);lines.setAllRowsVisible(true);
  lines.addColumn(l->value(l.codigo(),"—")).setHeader("Código");lines.addColumn(LineaNotaCreditoProveedorDto::descripcion).setHeader("Descripción").setFlexGrow(1);lines.addColumn(l->l.cantidad().toPlainString()).setHeader("Cantidad");lines.addColumn(l->money(l.precio())).setHeader("Precio");lines.addColumn(l->money(l.impuesto())).setHeader("Impuestos");lines.addColumn(l->money(l.total())).setHeader("Total");lines.setItems(x.lineas());
  Grid<AplicacionNotaCreditoProveedorDto> apps=new Grid<>(AplicacionNotaCreditoProveedorDto.class,false);apps.setAllRowsVisible(true);
  apps.addColumn(a->a.fecha()==null?"—":DATE.format(a.fecha().toLocalDate())).setHeader("Fecha");apps.addColumn(AplicacionNotaCreditoProveedorDto::factura).setHeader("Factura");apps.addColumn(AplicacionNotaCreditoProveedorDto::numeroProveedor).setHeader("No. proveedor");apps.addColumn(a->money(a.monto())).setHeader("Importe");apps.setItems(x.aplicaciones());
  d.add(new AppDetailSection("DOCUMENTO Y PROVEEDOR").field("Número",x.numero()).field("Estado",state(x.estado())).field("Fecha",DATE.format(x.fecha())).field("Proveedor",x.proveedor()).field("RNC / Identificación",x.identificacionProveedor()).field("No. proveedor",x.numeroProveedor()).field("NCF / e-NCF",x.numeroFiscal()).field("Moneda",x.moneda()).field("Factura relacionada",x.facturaRelacionada()).field("Motivo",reason(x.motivo())).field("Observación",x.observacion()).field("Subtotal",money(x.subtotal())).field("Impuestos",money(x.impuesto())).field("Total",money(x.total())).field("Aplicado",money(x.aplicado())).field("Disponible",money(x.disponible())),new H3("DETALLE"),lines,new H3("HISTORIAL DE APLICACIONES"),apps,new H4("Total aplicado: "+money(x.aplicado())));
  if(x.disponible().signum()>0&&x.estado()!=EstadoNotaCreditoProveedor.DRAFT&&x.estado()!=EstadoNotaCreditoProveedor.VOIDED&&can("notas_credito_proveedores.aplicar"))d.getFooter().add(new AppActionButton(ActionType.APPLY_CREDIT,ButtonSize.MAIN,"Aplicar crédito",e->{d.close();applyDialog(x);}));
  if(can("notas_credito_proveedores.imprimir"))d.getFooter().add(new AppActionButton(ActionType.PRINT,ButtonSize.MAIN,"Imprimir",e->UI.getCurrent().getPage().executeJs("window.print()")));
  if(x.estado()!=EstadoNotaCreditoProveedor.DRAFT&&x.estado()!=EstadoNotaCreditoProveedor.VOIDED&&can("notas_credito_proveedores.anular"))d.getFooter().add(new AppActionButton(ActionType.VOID,ButtonSize.MAIN,"Anular",e->voidDialog(x,d)));
  d.getFooter().add(new AppActionButton(ActionType.CLOSE,ButtonSize.MAIN,"Cerrar",e->d.close()));d.open();
 }catch(RuntimeException e){error(e,"No fue posible consultar la nota de crédito.");}}
 private void applyDialog(NotaCreditoProveedorDto summary){try{var x=service.get(summary.id());new SupplierCreditApplicationDialog(service,x,this::load).open();}catch(RuntimeException e){error(e,"No fue posible preparar la aplicación del crédito.");}}
 private void voidDialog(NotaCreditoProveedorDto x,Dialog parent){Dialog d=dialog("ANULAR NOTA DE CRÉDITO");TextArea reason=new TextArea("Motivo de anulación");reason.setRequiredIndicatorVisible(true);d.add(reason);d.getFooter().add(new AppActionButton(ActionType.VOID,ButtonSize.MAIN,"Anular",e->{try{service.voidNote(x.id(),x.version(),reason.getValue());d.close();parent.close();load();Notification.show("Nota de crédito anulada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible anular la nota.");}}),new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->d.close()));d.open();}

 private static NotaCreditoProveedorInput input(ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> supplier,DatePicker date,TextField number,TextField fiscal,ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> currency,BigDecimalField rate,Select<MotivoNotaCreditoProveedor> reason,TextField other,ComboBox<FacturaAplicacionCreditoDto> invoice,TextArea notes,List<LineDraft> lines,NotaCreditoProveedorDto current){return new NotaCreditoProveedorInput(id(supplier),date.getValue(),number.getValue(),fiscal.getValue(),id(currency),rate.getValue(),reason.getValue(),other.getValue(),invoice.getValue()==null?null:invoice.getValue().facturaId(),notes.getValue(),lines.stream().map(l->new LineaNotaCreditoProveedorInput(l.invoiceLineId(),l.productId(),l.description(),l.quantity(),l.price(),l.discount(),l.tax()==null?null:l.tax().id())).toList(),current==null?null:current.version());}
 private static void totals(List<LineDraft> lines,Span subtotal,Span discount,Span tax,Span total){BigDecimal s=BigDecimal.ZERO,d=BigDecimal.ZERO,t=BigDecimal.ZERO,g=BigDecimal.ZERO;if(!lines.isEmpty()){for(var l:lines){s=s.add(l.calculated().grossSubtotal());d=d.add(l.calculated().discount());t=t.add(l.calculated().taxAmount());g=g.add(l.calculated().total());}}subtotal.setText(money(s));discount.setText(money(d));tax.setText(money(t));total.setText(money(g));}private static Div totalBox(Span subtotal,Span discount,Span tax,Span total){Div box=new Div();box.addClassName("cc-invoice-totals");box.getStyle().set("margin-left","auto").set("width","min(420px,100%)");box.add(row("Subtotal",subtotal),row("Descuento",discount),row("Impuestos",tax),row("TOTAL NOTA",total));return box;}private static HorizontalLayout row(String name,Span value){HorizontalLayout r=new HorizontalLayout(new Span(name),value);r.setWidthFull();r.setJustifyContentMode(JustifyContentMode.BETWEEN);return r;}
 private static <T extends NotaCreditoProveedorCatalogosDto.Opcion> ComboBox<T> combo(String label,List<T> items){ComboBox<T> c=new ComboBox<>(label);c.setItems(items);c.setItemLabelGenerator(NotaCreditoProveedorCatalogosDto.Opcion::nombre);c.setClearButtonVisible(true);return c;}private static void select(ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> c,List<NotaCreditoProveedorCatalogosDto.Opcion> xs,UUID id){c.setValue(xs.stream().filter(x->Objects.equals(x.id(),id)).findFirst().orElse(null));}private static UUID id(ComboBox<NotaCreditoProveedorCatalogosDto.Opcion> c){return c.getValue()==null?null:c.getValue().id();}private static Div section(String title,Component...fields){Div d=new Div();d.addClassName("cc-form-section");d.add(new H3(title));Div f=new Div(fields);f.addClassName("cc-dialog-form");d.add(f);return d;}private static Dialog dialog(String title){Dialog d=new Dialog();d.setHeaderTitle(title);d.setWidth("min(1180px,96vw)");return d;}private static HorizontalLayout actions(){HorizontalLayout h=new HorizontalLayout();h.addClassName("cc-grid-actions");h.setSpacing(false);return h;}private static Span badge(EstadoNotaCreditoProveedor s){Span x=new Span(state(s));x.getElement().getThemeList().add("badge "+(s==EstadoNotaCreditoProveedor.APPLIED?"success":s==EstadoNotaCreditoProveedor.VOIDED?"error":s==EstadoNotaCreditoProveedor.DRAFT?"contrast":"primary"));return x;}private static String state(EstadoNotaCreditoProveedor s){if(s==null)return "Todos";return switch(s){case DRAFT->"Borrador";case AVAILABLE->"Disponible";case PARTIALLY_APPLIED->"Parcialmente aplicada";case APPLIED->"Aplicada";case VOIDED->"Anulada";};}private static String reason(MotivoNotaCreditoProveedor r){if(r==null)return "";return switch(r){case GOODS_RETURN->"Devolución de mercancía";case POST_PURCHASE_DISCOUNT->"Descuento posterior a la compra";case PRICE_DIFFERENCE->"Diferencia de precio";case BONUS->"Bonificación";case INVOICE_CORRECTION->"Corrección de factura";case DEFECTIVE_GOODS->"Mercancía defectuosa";case OTHER->"Otro";};}private static String money(BigDecimal v){return v==null?"—":String.format(Locale.US,"%,.2f",v);}private static String value(String v,String fallback){return v==null||v.isBlank()?fallback:v;}private static boolean can(String p){return TenantContext.principalActual().permisos().contains(p);}private static void error(RuntimeException e,String fallback){Notification.show(e instanceof ReglaNegocioException||e instanceof RecursoNoEncontradoException?e.getMessage():fallback);}
 private record LineDraft(UUID invoiceLineId,UUID productId,String code,String description,String unit,BigDecimal invoiced,BigDecimal quantity,BigDecimal price,BigDecimal discount,OrdenCompraCatalogosDto.ImpuestoOpcion tax,PurchaseOrderCalculationService.CalculatedLine calculated){}
}
