package com.citacloud.springboot.contacloud.app.views;

import com.citacloud.springboot.contacloud.app.dto.*;
import com.citacloud.springboot.contacloud.app.security.TenantContext;
import com.citacloud.springboot.contacloud.app.services.*;
import com.citacloud.springboot.contacloud.app.views.components.*;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.*;
import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;
import java.util.*;

@Route(value="unidades-medida",layout=MainLayout.class)
@PageTitle("Unidades de medida | ContaCloud")
@PermitAll
public class UnidadesMedidaView extends VerticalLayout implements BeforeEnterObserver,BeforeLeaveObserver {
    private final UnitOfMeasureService service;private final EmpresaModuloService modules;
    private final TextField search=new TextField("Buscar");private final Select<String> state=new Select<>();
    private final AppGrid<UnidadMedidaDto> grid=new AppGrid<>(UnidadMedidaDto.class);private final AppPagination pagination;
    private Dialog openForm;private Dirty dirty;

    public UnidadesMedidaView(UnitOfMeasureService service,EmpresaModuloService modules){this.service=service;this.modules=modules;addClassName("cc-page");setPadding(false);setSpacing(false);setWidthFull();Component create=can("unidades_medida.crear")?new AppActionButton(ActionType.NEW,ButtonSize.MAIN,"Nueva unidad de medida",e->form(null)):null;add(create==null?new AppPageHeader("UNIDADES DE MEDIDA","Administra las unidades de medida utilizadas en productos, servicios y operaciones de inventario."):new AppPageHeader("UNIDADES DE MEDIDA","Administra las unidades de medida utilizadas en productos, servicios y operaciones de inventario.",create));search.setPlaceholder("Buscar por nombre o abreviatura...");search.setClearButtonVisible(true);search.setValueChangeMode(ValueChangeMode.LAZY);search.setValueChangeTimeout(400);state.setLabel("Estado");state.setItems("Todos","Activo","Inactivo");state.setValue("Todos");search.addValueChangeListener(e->{if(e.isFromClient())reset();});state.addValueChangeListener(e->{if(e.isFromClient())reset();});HorizontalLayout filters=new HorizontalLayout(search,state);filters.addClassName("cc-filter-bar");filters.setAlignItems(Alignment.END);filters.setWidthFull();configureGrid();pagination=new AppPagination(r->load());add(filters,grid,pagination);}

    @Override public void beforeEnter(BeforeEnterEvent event){if(!modules.habilitado("INVENTARIO")||!can("unidades_medida.ver")){Notification.show("No tienes permiso para acceder a esta opción.");event.rerouteTo(DashboardView.class);return;}load();}
    @Override public void beforeLeave(BeforeLeaveEvent event){if(openForm==null||dirty==null||!dirty.value)return;var action=event.postpone();confirmDiscard(()->{dirty.value=false;openForm.close();action.proceed();});}

    private void configureGrid(){grid.addColumn(UnidadMedidaDto::nombre).setHeader("Nombre").setFlexGrow(1);grid.addColumn(UnidadMedidaDto::abreviatura).setHeader("Abreviatura").setAutoWidth(true).setFlexGrow(0);grid.addComponentColumn(u->badge(u.activo())).setHeader("Estado").setAutoWidth(true).setFlexGrow(0);grid.addComponentColumn(this::actions).setHeader("Acciones").setAutoWidth(true).setFlexGrow(0);grid.setEmptyStateText(emptyMessage());}
    private Component actions(UnidadMedidaDto unit){HorizontalLayout actions=new HorizontalLayout();actions.addClassName("cc-grid-actions");actions.setPadding(false);actions.setSpacing(false);actions.add(new AppActionButton(ActionType.VIEW,ButtonSize.GRID_ACTION,"Ver unidad de medida",e->detail(unit.id())));if(can("unidades_medida.editar"))actions.add(new AppActionButton(ActionType.EDIT,ButtonSize.GRID_ACTION,"Editar unidad de medida",e->form(unit.id())));return actions;}
    private void load(){try{var request=pagination.currentRequest();var page=service.searchUnits(search.getValue(),stateFilter(),request.page(),request.size());grid.setItems(page.getContent());boolean filtered=!search.getValue().isBlank()||stateFilter()!=null;grid.setEmptyStateText(filtered?"No se encontraron unidades de medida con los filtros seleccionados.":emptyMessage());pagination.setTotal(page.getTotalElements());}catch(RuntimeException ex){error(ex,"No fue posible cargar las unidades de medida.");}}
    private void reset(){pagination.reset();load();}private Boolean stateFilter(){return switch(state.getValue()==null?"Todos":state.getValue()){case"Activo"->true;case"Inactivo"->false;default->null;};}
    private String emptyMessage(){return can("unidades_medida.crear")?"No hay unidades de medida registradas. Crea la primera unidad de medida para comenzar.":"No hay unidades de medida registradas.";}

    private void form(UUID id){try{UnidadMedidaDto current=id==null?null:service.getUnit(id);Dialog dialog=dialog(current==null?"NUEVA UNIDAD DE MEDIDA":"EDITAR UNIDAD DE MEDIDA");TextField name=new TextField("Nombre");name.setRequiredIndicatorVisible(true);name.setMaxLength(80);TextField abbreviation=new TextField("Abreviatura");abbreviation.setRequiredIndicatorVisible(true);abbreviation.setMaxLength(20);TextArea description=new TextArea("Descripción");description.setMaxLength(500);description.addClassName("cc-dialog-span-2");Checkbox active=new Checkbox("Activo",true);active.addClassName("cc-dialog-span-2");if(current!=null){name.setValue(current.nombre());abbreviation.setValue(current.abreviatura());description.setValue(value(current.descripcion()));active.setValue(current.activo());active.setReadOnly(true);}Dirty changes=new Dirty();name.addValueChangeListener(e->changes.mark(e.isFromClient()));abbreviation.addValueChangeListener(e->changes.mark(e.isFromClient()));description.addValueChangeListener(e->changes.mark(e.isFromClient()));dialog.add(formLayout(name,abbreviation,description,active));AppActionButton save=new AppActionButton(ActionType.SAVE,ButtonSize.MAIN,"Guardar",null);save.addClickListener(e->{save.setEnabled(false);try{UnidadMedidaInput input=new UnidadMedidaInput(name.getValue(),abbreviation.getValue(),description.getValue(),active.getValue(),current==null?null:current.version());if(current==null)service.createUnit(input);else service.updateUnit(current.id(),input);changes.value=false;dialog.close();load();Notification.show(current==null?"Unidad de medida creada correctamente.":"Unidad de medida actualizada correctamente.");}catch(RuntimeException ex){save.setEnabled(true);error(ex,"No fue posible guardar la unidad de medida.");}});dialog.getFooter().add(save,new AppActionButton(ActionType.CANCEL,ButtonSize.MAIN,"Cancelar",e->closeForm(dialog,changes)));dialog.setCloseOnEsc(false);dialog.setCloseOnOutsideClick(false);dialog.addDialogCloseActionListener(e->closeForm(dialog,changes));openForm=dialog;dirty=changes;dialog.addClosedListener(e->{if(openForm==dialog){openForm=null;dirty=null;}});dialog.open();}catch(RuntimeException ex){error(ex,"No fue posible abrir la unidad de medida.");}}

    private void detail(UUID id){try{UnidadMedidaDto unit=service.getUnit(id);Dialog dialog=dialog("UNIDAD DE MEDIDA");Div heading=new Div(new H2(unit.nombre()),badge(unit.activo()));heading.addClassName("cc-detail-heading");dialog.add(heading,new AppDetailSection("INFORMACIÓN GENERAL").field("Nombre",unit.nombre()).field("Abreviatura",unit.abreviatura()).field("Descripción",unit.descripcion()==null?"Sin descripción":unit.descripcion()));if(can("unidades_medida.editar"))dialog.getFooter().add(new AppActionButton(ActionType.EDIT,ButtonSize.MAIN,"Editar",e->{dialog.close();form(unit.id());}));if(unit.activo()&&can("unidades_medida.desactivar"))dialog.getFooter().add(new AppActionButton(ActionType.DEACTIVATE,ButtonSize.MAIN,"Desactivar",e->confirmState(unit,dialog)));if(!unit.activo()&&can("unidades_medida.reactivar"))dialog.getFooter().add(new AppActionButton(ActionType.ACTIVATE,ButtonSize.MAIN,"Reactivar",e->confirmState(unit,dialog)));dialog.getFooter().add(new AppActionButton(ActionType.CLOSE,ButtonSize.MAIN,"Cerrar",e->dialog.close()));dialog.open();}catch(RuntimeException ex){error(ex,"No fue posible consultar la unidad de medida.");}}
    private void confirmState(UnidadMedidaDto unit,Dialog parent){boolean deactivate=unit.activo();ConfirmDialog confirm=new ConfirmDialog();confirm.setHeader(deactivate?"Desactivar unidad de medida":"Reactivar unidad de medida");confirm.setText(deactivate?"La unidad dejará de estar disponible para nuevas asignaciones. Los documentos históricos no serán modificados. ¿Deseas continuar?":"La unidad volverá a estar disponible para nuevas asignaciones. ¿Deseas continuar?");confirm.setCancelable(true);confirm.setCancelText("Cancelar");confirm.setConfirmText(deactivate?"Desactivar":"Reactivar");if(deactivate)confirm.setConfirmButtonTheme("error primary");confirm.addConfirmListener(e->{try{if(deactivate)service.deactivateUnit(unit.id(),unit.version());else service.reactivateUnit(unit.id(),unit.version());parent.close();load();Notification.show(deactivate?"Unidad de medida desactivada correctamente.":"Unidad de medida reactivada correctamente.");}catch(RuntimeException ex){error(ex,"No fue posible cambiar el estado de la unidad de medida.");}});confirm.open();}

    private static Div formLayout(Component... fields){Div form=new Div(fields);form.addClassName("cc-dialog-form");return form;}private static Dialog dialog(String title){Dialog dialog=new Dialog();dialog.setHeaderTitle(title);dialog.setWidth("min(760px, 96vw)");return dialog;}private static Span badge(boolean active){Span badge=new Span(active?"Activo":"Inactivo");badge.getElement().getThemeList().add("badge "+(active?"success":"contrast"));return badge;}private static String value(String value){return value==null?"":value;}
    private static boolean can(String permission){return TenantContext.principalActual().permisos().contains(permission);}private static void closeForm(Dialog dialog,Dirty dirty){if(!dirty.value){dialog.close();return;}confirmDiscard(()->{dirty.value=false;dialog.close();});}private static void confirmDiscard(Runnable discard){ConfirmDialog confirm=new ConfirmDialog();confirm.setHeader("Cambios sin guardar");confirm.setText("Hay cambios sin guardar. ¿Deseas descartarlos?");confirm.setCancelable(true);confirm.setCancelText("Continuar editando");confirm.setConfirmText("Descartar cambios");confirm.setConfirmButtonTheme("error primary");confirm.addConfirmListener(e->discard.run());confirm.open();}private static void error(RuntimeException ex,String fallback){String message=ex instanceof ReglaNegocioException||ex instanceof RecursoNoEncontradoException?ex.getMessage():fallback;Notification.show(message==null||message.isBlank()?fallback:message);}private static final class Dirty{private boolean value;void mark(boolean client){if(client)value=true;}}
}
